/**
 * Roman Urdu → Urdu script dictionary (600+ keys including spelling variants).
 * Original vocabulary for the Pakistani context; not copied from third-party transliteration packages.
 */

function buildMap(): Map<string, string> {
  const m = new Map<string, string>();
  const add = (keys: readonly string[], urdu: string): void => {
    for (const k of keys) {
      const n = k.toLowerCase().trim();
      if (n.length > 0) m.set(n, urdu);
    }
  };

  const groups: Array<{ ur: string; keys: string[] }> = [
    { ur: 'السلام علیکم', keys: ['assalam o alaikum', 'assalam-o-alaikum', 'assalamoalaikum', 'salam'] },
    { ur: 'وعلیکم السلام', keys: ['walaikum assalam', 'walaikum salam', 'walekum assalam'] },
    { ur: 'شکریہ', keys: ['shukriya', 'shukria', 'shukariya'] },
    { ur: 'مہربانی', keys: ['mehrbani', 'meharbani', 'meherbani'] },
    { ur: 'خدا حافظ', keys: ['khuda hafiz', 'khudaafiz'] },
    { ur: 'اللہ حافظ', keys: ['allah hafiz', 'allahafiz'] },
    { ur: 'انشاءاللہ', keys: ['inshallah', 'in sha allah', 'inshaa allah'] },
    { ur: 'ماشاءاللہ', keys: ['mashallah', 'ma sha allah'] },
    { ur: 'اچھا', keys: ['acha', 'achha', 'accha'] },
    { ur: 'ٹھیک', keys: ['theek', 'teek', 'thiik', 'thik', 'theekhai'] },
    { ur: 'کیا', keys: ['kya', 'kia', 'kyaa', 'kiya'] },
    { ur: 'ہے', keys: ['hai', 'hay', 'he', 'hy'] },
    { ur: 'ہیں', keys: ['hain', 'hayn', 'hen', 'hin'] },
    { ur: 'نہیں', keys: ['nahi', 'nahin', 'naheen', 'nai', 'nahee'] },
    { ur: 'بھائی', keys: ['bhai', 'bhay', 'bhayi', 'bhaiya'] },
    { ur: 'یار', keys: ['yaar', 'yar'] },
    { ur: 'دوست', keys: ['dost', 'doston'] },
    { ur: 'گھر', keys: ['ghar', 'gher', 'gharr'] },
    { ur: 'کام', keys: ['kam', 'kaam'] },
    { ur: 'پیسہ', keys: ['paisa', 'pesa', 'paisay', 'paise'] },
    { ur: 'وقت', keys: ['waqt', 'wakt', 'vaqt'] },
    { ur: 'دن', keys: ['din', 'dinon', 'dino'] },
    { ur: 'رات', keys: ['raat', 'rat', 'raatein'] },
    { ur: 'کھانا', keys: ['khana', 'khaana', 'khanna'] },
    { ur: 'پانی', keys: ['pani', 'paani'] },
    { ur: 'چائے', keys: ['chai', 'chay', 'chaay'] },
    { ur: 'کتاب', keys: ['kitab', 'kitaab'] },
    { ur: 'اسکول', keys: ['school', 'skool', 'iskool'] },
    { ur: 'گاڑی', keys: ['gari', 'gaari'] },
    { ur: 'بچہ', keys: ['bacha', 'bachha', 'baccha', 'bachay'] },
    { ur: 'لوگ', keys: ['log', 'logon', 'loug'] },
    { ur: 'آدمی', keys: ['aadmi', 'aadmee'] },
    { ur: 'عورت', keys: ['aurat', 'aurtein'] },
    { ur: 'بات', keys: ['baat', 'bat', 'baatein'] },
    { ur: 'کچھ', keys: ['kuch', 'kuchh'] },
    { ur: 'سب', keys: ['sab', 'sabb'] },
    { ur: 'آپ', keys: ['aap', 'ap'] },
    { ur: 'میں', keys: ['mein', 'main', 'me', 'mai'] },
    { ur: 'تم', keys: ['tum', 'tumharay'] },
    { ur: 'وہ', keys: ['woh', 'wo', 'voh'] },
    { ur: 'ہم', keys: ['hum', 'ham'] },
    { ur: 'یہ', keys: ['yeh', 'ye', 'yay'] },
    { ur: 'کوئی', keys: ['koi', 'koyi', 'koe'] },
    { ur: 'کہاں', keys: ['kahan', 'kahaan', 'kidhar', 'kidher'] },
    { ur: 'کیوں', keys: ['kyun', 'kiun', 'kun', 'kyoon'] },
    { ur: 'کب', keys: ['kab', 'kabhi', 'kabhee'] },
    { ur: 'کیسا', keys: ['kaisa', 'kaesa', 'kaisay', 'kaise'] },
    { ur: 'کتنا', keys: ['kitna', 'kitney', 'kitni', 'kitnay'] },
    { ur: 'بہت', keys: ['bohat', 'bahut', 'bohot', 'bht'] },
    { ur: 'صرف', keys: ['sirf', 'sarf'] },
    { ur: 'پھر', keys: ['phir', 'fer', 'phr'] },
    { ur: 'اب', keys: ['ab', 'abhi', 'abhee'] },
    { ur: 'پہلے', keys: ['pehle', 'pahle', 'pehlay', 'pahlay'] },
    { ur: 'بعد', keys: ['baad', 'bad'] },
    { ur: 'ساتھ', keys: ['saath', 'sath'] },
    { ur: 'اندر', keys: ['andar', 'ander'] },
    { ur: 'باہر', keys: ['bahar', 'baahar', 'bahir'] },
    { ur: 'اوپر', keys: ['upar', 'oopar', 'uper'] },
    { ur: 'نیچے', keys: ['neeche', 'neche', 'neechay'] },
    { ur: 'ادھر', keys: ['idhar', 'ithar', 'udhar', 'uthar', 'idher'] },
    { ur: 'کل', keys: ['kal'] },
    { ur: 'آج', keys: ['aaj', 'aj'] },
    { ur: 'پرسوں', keys: ['parso', 'parsu'] },
    { ur: 'صبح', keys: ['subah', 'subha', 'soobah'] },
    { ur: 'دوپہر', keys: ['dopahar', 'dopeher'] },
    { ur: 'شام', keys: ['sham', 'shaam'] },
    { ur: 'کرنا', keys: ['karna', 'krna'] },
    { ur: 'جانا', keys: ['jana', 'jaana'] },
    { ur: 'آنا', keys: ['aana', 'ana'] },
    { ur: 'دینا', keys: ['dena', 'daina'] },
    { ur: 'لینا', keys: ['lena', 'laina'] },
    { ur: 'بولنا', keys: ['bolna', 'boolna'] },
    { ur: 'سوچنا', keys: ['sochna'] },
    { ur: 'دیکھنا', keys: ['dekhna', 'dekhny'] },
    { ur: 'سننا', keys: ['sunna'] },
    { ur: 'پڑھنا', keys: ['padhna', 'parhna'] },
    { ur: 'لیکھنا', keys: ['likhna', 'likhnay'] },
    { ur: 'پینا', keys: ['peena', 'pina'] },
    { ur: 'سونا', keys: ['sona', 'sowna'] },
    { ur: 'اٹھنا', keys: ['uthna', 'utthna'] },
    { ur: 'بیٹھ جانا', keys: ['baith jana', 'baithna'] },
    { ur: 'چلنا', keys: ['chalna'] },
    { ur: 'دوڑنا', keys: ['dorna', 'bhagna'] },
    { ur: 'رونا', keys: ['rona'] },
    { ur: 'ہنسنا', keys: ['hasna', 'hansna'] },
    { ur: 'ایک', keys: ['ek', 'aik', 'ikk'] },
    { ur: 'دو', keys: ['do', 'dou'] },
    { ur: 'تین', keys: ['teen', 'tiin'] },
    { ur: 'چار', keys: ['char', 'chaar'] },
    { ur: 'پانچ', keys: ['panch', 'paanch'] },
    { ur: 'چھ', keys: ['chhe', 'chhey', 'chh'] },
    { ur: 'سات', keys: ['saat'] },
    { ur: 'آٹھ', keys: ['aath', 'aatth'] },
    { ur: 'نو', keys: ['nau', 'naw'] },
    { ur: 'دس', keys: ['das', 'dus'] },
    { ur: 'بیس', keys: ['bis', 'bees'] },
    { ur: 'تیس', keys: ['tees'] },
    { ur: 'چالیس', keys: ['chalis', 'chaalees'] },
    { ur: 'پچاس', keys: ['pachas', 'pachaas'] },
    { ur: 'سو', keys: ['sau', 'soo'] },
    { ur: 'ہزار', keys: ['hazar', 'hazaar'] },
    { ur: 'لاکھ', keys: ['lakh', 'laakh'] },
    { ur: 'خوش', keys: ['khush'] },
    { ur: 'اداس', keys: ['udas', 'udasd', 'udaas'] },
    { ur: 'غصہ', keys: ['gussa', 'ghussa'] },
    { ur: 'درد', keys: ['dard'] },
    { ur: 'پیار', keys: ['pyar', 'piyar', 'pyaar'] },
    { ur: 'محبت', keys: ['mohabbat', 'muhabbat'] },
    { ur: 'نفرت', keys: ['nafrat'] },
    { ur: 'ڈر', keys: ['darr', 'dar'] },
    { ur: 'امید', keys: ['umeed'] },
    { ur: 'یقین', keys: ['yaqeen', 'yakeen'] },
    { ur: 'شک', keys: ['shak', 'shakk'] },
    { ur: 'زندگی', keys: ['zindagi', 'zindagee'] },
    { ur: 'موت', keys: ['maut'] },
    { ur: 'خواب', keys: ['khwab', 'khwaab'] },
    { ur: 'آزادی', keys: ['azadi', 'aazaadi'] },
  ];

  for (const g of groups) add(g.keys, g.ur);

  const bulk: Array<[string, readonly string[]]> = [
    ['مکان', ['makaan', 'makan', 'makkan']],
    ['دکان', ['dukaan', 'dukan', 'dukaann']],
    ['سڑک', ['sarak', 'sarrak', 'sadak']],
    ['پل', ['pul', 'pull']],
    ['پارک', ['park', 'paark']],
    ['ہسپتال', ['hospital', 'haspatal', 'hispatal']],
    ['دوا', ['dawa', 'dawaa', 'dawai']],
    ['ڈاکٹر', ['doctor', 'daaktar', 'daktar']],
    ['نرس', ['nurse', 'nars']],
    ['استاد', ['ustaad', 'ustad', 'ustaadh']],
    ['طالب علم', ['talib', 'talib ilm', 'taalib']],
    ['کلاس', ['class', 'klaas', 'klass']],
    ['امتحان', ['imtehaan', 'imtehan', 'exam']],
    ['نمبر', ['number', 'nambar', 'nambur']],
    ['سوال', ['sawaal', 'sawal', 'sual']],
    ['جواب', ['jawaab', 'jawab', 'jwab']],
    ['سچ', ['sach', 'such', 'sachai']],
    ['جھوٹ', ['jhoot', 'jhooth', 'jhoot']],
    ['سفید', ['safaid', 'safed', 'sufaid']],
    ['سیاہ', ['siyah', 'syaah', 'kaala']],
    ['نیلا', ['neela', 'neelay', 'neeli']],
    ['سبز', ['sabz', 'sabz rang']],
    ['پیلا', ['peela', 'peelay', 'peeli']],
    ['لال', ['laal', 'lal']],
    ['بادل', ['baadal', 'badal', 'baadil']],
    ['بارش', ['barish', 'baarish', 'barsaat']],
    ['دھوپ', ['dhoop', 'dhoop mein']],
    ['ہوا', ['hawa', 'hawaa']],
    ['آگ', ['aag', 'aagh']],
    ['برف', ['barf', 'baraf']],
    ['درخت', ['darakht', 'drakht', 'darkhat']],
    ['پھول', ['phool', 'phul', 'phoolon']],
    ['پھل', ['phal', 'phaloon', 'phalon']],
    ['سبزی', ['sabzi', 'sabzee']],
    ['گوشت', ['gosht', 'goshtt', 'gosh']],
    ['دودھ', ['doodh', 'dudh', 'dhoodh']],
    ['روٹی', ['roti', 'rooti', 'rotee']],
    ['چاول', ['chaawal', 'chawal', 'chaval']],
    ['دال', ['daal', 'daalain', 'daalen']],
    ['مرغی', ['murghi', 'murgh', 'murgi']],
    ['مچھلی', ['machhli', 'machli', 'machlee']],
    ['انڈا', ['anda', 'anday', 'andey']],
    ['چینی', ['cheeni', 'chini', 'cheenee']],
    ['نمک', ['namak', 'nammak', 'noomak']],
    ['مسالہ', ['masala', 'masaala', 'masalay']],
    ['تیل', ['tail', 'teel', 'tayl']],
    ['دہی', ['dahi', 'dehee', 'dahii']],
    ['سونا', ['sona', 'sonay', 'suuna']],
    ['چاندی', ['chaandi', 'chandi', 'chaandee']],
    ['لوہا', ['loha', 'lohay', 'louha']],
    ['کپڑا', ['kapra', 'kaprra', 'kaprray']],
    ['جوتا', ['joota', 'jootay', 'jooti']],
    ['ٹوپی', ['topee', 'topi', 'toopii']],
    ['چادر', ['chaadar', 'chadar', 'chaadarr']],
    ['بستر', ['bistar', 'bistarr', 'bistaray']],
    ['تکیہ', ['takiya', 'takiyah', 'takiye']],
    ['دروازہ', ['darwaza', 'darwaaza', 'darwazay']],
    ['کھڑکی', ['khirki', 'khidki', 'khirkee']],
    ['چھت', ['chhat', 'chatt', 'chhat par']],
    ['فرش', ['farsh', 'farsh par', 'farrsh']],
    ['دیوار', ['deewaar', 'deewar', 'dewaar']],
    ['الماری', ['almari', 'almaree', 'almaari']],
    ['میز', ['maiz', 'maeez', 'meiz']],
    ['کرسی', ['kursi', 'kursian', 'kursees']],
    ['برتن', ['bartan', 'bartann']],
    ['چمچ', ['chamach', 'chammach', 'chamcha']],
    ['پلیٹ', ['plate', 'plait', 'platein']],
    ['گلاس', ['glass', 'gilaas', 'gilass']],
    ['کپ', ['cup', 'kapp', 'kap']],
    ['چاقو', ['chaku', 'chaaku', 'chakoo']],
    ['چھری', ['churee', 'chhuree', 'churee']],
    ['سوزن', ['soozan', 'sozan', 'sui']],
    ['دھاگہ', ['dhaaga', 'dhaga', 'dhaagay']],
    ['آئینہ', ['aaina', 'aainaa', 'ayna']],
    ['کنگھی', ['kanghi', 'kanghee', 'kangi']],
    ['صابن', ['saabun', 'sabun', 'soap']],
    ['تولیہ', ['towl', 'towel', 'tawliya']],
    ['بجلی', ['bijli', 'bijlee', 'bijli ka']],
    ['پنکھا', ['pankha', 'pankhay', 'pankhay']],
    ['شہر', ['shehar', 'shehr', 'sheher']],
    ['گاؤں', ['gaon', 'gaaon', 'gaav']],
    ['صوبہ', ['soobah', 'sooba', 'subah e']],
    ['ملک', ['mulk', 'mulk mein', 'mulk ka']],
    ['دنیا', ['dunya', 'duniya', 'duniyaa']],
    ['آسمان', ['aasmaan', 'asman', 'asmaan']],
    ['زمین', ['zameen', 'zameen par', 'zameeni']],
    ['سمندر', ['samandar', 'samundar', 'samundarr']],
    ['دریا', ['darya', 'daryaa', 'darya ka']],
    ['جنگل', ['jangal', 'jungle', 'jangal mein']],
    ['صحرا', ['sahra', 'sehra', 'sehra mein']],
    ['پہاڑ', ['pahaarr', 'pahar', 'pahaad']],
    ['وادی', ['waadi', 'wadi', 'waadee']],
    ['جزیرہ', ['jazeera', 'jazeerah', 'jazire']],
    ['ساحل', ['saahil', 'sahil', 'saahil par']],
    ['بندرگاہ', ['bandargaah', 'bandargah', 'bandar gaah']],
    ['اسٹیشن', ['station', 'satteshan', 'istayshan']],
    ['بس', ['bus', 'bas', 'buss']],
    ['ٹرین', ['train', 'tareen', 'tren']],
    ['جہاز', ['jahaz', 'jahaaz', 'hawai jahaz']],
    ['کشتی', ['kashti', 'kashtee', 'kashtiyan']],
    ['موٹر سائیکل', ['motor', 'motor cycle', 'motorcycle']],
    ['سائیکل', ['cycle', 'saikil', 'saaykil']],
    ['ٹیکسی', ['taxi', 'taksii', 'teksi']],
    ['رکشہ', ['riksha', 'rickshaw', 'rikshay']],
    ['ٹریفک', ['traffic', 'trafik', 'traffick']],
    ['سگنل', ['signal', 'siganal', 'signaal']],
    ['چوراہا', ['chowrangi', 'choraha', 'chaurangi']],
    ['گلی', ['gali', 'galiyan', 'gallee']],
    ['محلہ', ['mohalla', 'muhallay', 'mohallay']],
    ['بازار', ['bazaar', 'bazaar mein', 'bazar']],
    ['قیمت', ['qeemat', 'qeemt', 'keemat']],
    ['سودا', ['soda', 'souda', 'sauda']],
    ['رقم', ['raqam', 'raqmay', 'rakam']],
    ['بینک', ['bank', 'baenak', 'bank mein']],
    ['اکاؤنٹ', ['account', 'akaunt', 'akount']],
    ['چیک', ['cheque', 'check', 'chek']],
    ['کارڈ', ['card', 'kaard', 'karrrrd']],
    ['بل', ['bill', 'bil', 'bills']],
    ['رسید', ['raseed', 'rasheed', 'receipt']],
    ['ٹیکس', ['tax', 'taks', 'tex']],
    ['پگار', ['pagar', 'paggar', 'pagaar']],
    ['ملازمت', ['mulazmat', 'mulazamat', 'naukri']],
    ['دفتر', ['daftar', 'daftarr', 'office']],
    ['میٹنگ', ['meeting', 'meating', 'meeting mein']],
    ['پروجیکٹ', ['project', 'projekt', 'projeckt']],
    ['رپورٹ', ['report', 'ripot', 'reporting']],
    ['فائل', ['file', 'faayl', 'files']],
    ['کاغذ', ['kaaghaz', 'kaghaz', 'kagaz']],
    ['قلم', ['qalam', 'kalam', 'qalaam']],
    ['ربڑ', ['rubber', 'rabaar', 'rubbr']],
    ['پنسل', ['pencil', 'pensil', 'pensal']],
    ['ریزش', ['sharpner', 'reshar', 'sharpener']],
    ['بستہ', ['basta', 'bastaa', 'school bag']],
    ['بورڈ', ['board', 'borrd', 'blackboard']],
    ['چاک', ['chaak', 'chaakk', 'chalk']],
    ['نقشہ', ['naqsha', 'naqshaa', 'naksha']],
    ['پیمائش', ['paimaish', 'paimaaish', 'nap']],
    ['وزن', ['wazan', 'wazn', 'wazan karna']],
    ['لمبائی', ['lambai', 'lambayee', 'lambayi']],
    ['چوڑائی', ['chorai', 'chourai', 'chorrayi']],
    ['اونچائی', ['oonchai', 'unchai', 'oonchayee']],
    ['رفتار', ['raftaar', 'raftar', 'speed']],
    ['تاریخ', ['taareekh', 'tareekh', 'tarikh']],
    ['ہفتہ', ['hafta', 'haftay', 'haftay ka']],
    ['مہینہ', ['maheena', 'mahina', 'maheenay']],
    ['سال', ['saal', 'saal ka', 'saalon']],
    ['منٹ', ['minute', 'minat', 'mint']],
    ['گھنٹہ', ['ghanta', 'ghantay', 'ghantay ka']],
    ['سیکنڈ', ['second', 'sekand', 'secand']],
    ['پیر', ['peer', 'pir', 'peer ko']],
    ['منگل', ['mangal', 'mangal ko', 'mangal']],
    ['بدھ', ['budh', 'budhh', 'budh ko']],
    ['جمعرات', ['jumairaat', 'jumarat', 'jumeraat']],
    ['جمعہ', ['jumma', 'jummah', 'jumma mubarak']],
    ['اتوار', ['ittwaar', 'itwaar', 'haftay ka akhri din']],
    ['جنوری', ['janwari', 'january', 'janwari ka']],
    ['فروری', ['farwari', 'february', 'farwari ka']],
    ['مارچ', ['maarch', 'march', 'maarch ka']],
    ['اپریل', ['april', 'aprayl', 'april ka']],
    ['مئی', ['mai', 'may', 'mai ka']],
    ['جون', ['june', 'joon', 'june ka']],
    ['جولائی', ['july', 'julai', 'julaay']],
    ['اگست', ['august', 'agast', 'augast']],
    ['ستمبر', ['sitambar', 'september', 'sitambar ka']],
    ['اکتوبر', ['aktobar', 'october', 'oktober']],
    ['نومبر', ['nombar', 'november', 'nomember']],
    ['دسمبر', ['disambar', 'december', 'disamber']],
    ['عید', ['eid', 'eed', 'eid mubarak']],
    ['رمضان', ['ramzan', 'ramadan', 'ramzaan']],
    ['حج', ['hajj', 'haj', 'haj ka']],
    ['نماز', ['namaaz', 'namaz', 'namaazain']],
    ['روزہ', ['roza', 'rozay', 'roza rakhna']],
    ['مسجد', ['masjid', 'masjiday', 'masjid mein']],
    ['مندر', ['mandir', 'mandirr', 'mandir mein']],
    ['گرجا', ['girja', 'church', 'girjay']],
    ['شادی', ['shaadi', 'shadi', 'shaadee']],
    ['دعوت', ['dawat', 'dawatt', 'dawat par']],
    ['مہمان', ['mehmaan', 'mehman', 'mehmaano']],
    ['دولہا', ['dulha', 'doolha', 'dulhay']],
    ['دلہن', ['dulhan', 'doolhan', 'dulhann']],
    ['رشتہ', ['rishta', 'rishtaa', 'rishtay']],
    ['خاندان', ['khaandaan', 'khandan', 'khaandaan ka']],
    ['والد', ['walid', 'waalid', 'baap']],
    ['والدہ', ['walida', 'waalida', 'maan']],
    ['بیٹا', ['beta', 'bayta', 'betay']],
    ['بیٹی', ['beti', 'baytee', 'betiyan']],
    ['ماں', ['maan', 'maa', 'ma']],
    ['بہن', ['behn', 'bahan', 'bahen']],
    ['دادا', ['dada', 'daada', 'dadajee']],
    ['دادی', ['dadi', 'daadee', 'dadijaan']],
    ['نانا', ['nana', 'naana', 'nanajee']],
    ['نانی', ['nani', 'naanee', 'nanijaan']],
    ['چچا', ['chacha', 'chachaa', 'chachoo']],
    ['چچی', ['chachi', 'chachee', 'chachiyan']],
    ['ماما', ['mama', 'maama', 'mamoo']],
    ['مامی', ['mami', 'maamee', 'mamiyan']],
    ['سالا', ['sala', 'saala', 'salay']],
    ['سالی', ['sali', 'saalee', 'saliyan']],
    ['سسر', ['sasur', 'saasur', 'sasurr']],
    ['ساس', ['saas', 'saasu', 'saasain']],
    ['شوہر', ['shohar', 'shauhar', 'miyaa']],
    ['بیوی', ['biwi', 'bivee', 'begum']],
    ['پڑوسی', ['parosi', 'parosee', 'parosiyon']],
    ['دشمن', ['dushman', 'dushmann', 'dushmano']],
    ['ملاقات', ['mulaqaat', 'mulaqat', 'mulaqaatein']],
    ['معاف', ['maaf', 'maafi', 'maaf karna']],
    ['بیماری', ['bemari', 'bemaari', 'bemariyan']],
    ['علاج', ['ilaaj', 'elaj', 'ilaaj karna']],
    ['ٹیکہ', ['teeka', 'tika', 'teekay']],
    ['ویکسین', ['vaccine', 'waksin', 'veksin']],
    ['خون', ['khoon', 'khun', 'khoon ka']],
    ['ہڈی', ['haddi', 'haddee', 'haddiyan']],
    ['دماغ', ['dimaagh', 'dimagh', 'dimaagh ka']],
    ['دل', ['dil', 'dil ka', 'dilon']],
    ['جگر', ['jigar', 'jigarr', 'jigar ka']],
    ['آنکھ', ['aankh', 'ankh', 'aankhein']],
    ['کان', ['kaan', 'kaan ka', 'kaanon']],
    ['ناک', ['naak', 'naak ka', 'naak se']],
    ['منہ', ['munh', 'muh', 'moonh']],
    ['دانت', ['daant', 'dant', 'daanton']],
    ['زبان', ['zubaan', 'zuban', 'zubaan ka']],
    ['بال', ['baal', 'baalon', 'baal ka']],
    ['ہاتھ', ['haath', 'hath', 'haathon']],
    ['انگلی', ['ungli', 'unglee', 'ungliyaan']],
    ['پاؤں', ['paon', 'paoon', 'paon ka']],
    ['گھٹنا', ['ghutna', 'ghutnay', 'ghutnon']],
    ['کندھا', ['kandha', 'kandhay', 'kandhay par']],
    ['پیٹ', ['pet', 'peet', 'pet ka']],
    ['گردن', ['gardan', 'gardan par', 'gardan ka']],
    ['سر', ['sar', 'sarr', 'sir']],
    ['چہرہ', ['chehra', 'chehrah', 'chehray']],
    ['مسکرانا', ['muskurana', 'muskuraana', 'muskurahat']],
    ['خوف', ['khauf', 'khouf', 'dar']],
    ['غم', ['gham', 'ghamm', 'gham mein']],
    ['ذلت', ['zillat', 'zillatt', 'ruswai']],
    ['کامیاب', ['kaamyaab', 'kamyab', 'kaamyaabi']],
    ['ناکام', ['naakaam', 'nakam', 'nakami']],
    ['مایوس', ['mayoos', 'mayus', 'umeed tootna']],
    ['کمزور', ['kamzor', 'kamzoor', 'kamzori']],
    ['مضبوط', ['mazboot', 'mazbuut', 'mazbooti']],
    ['صحت مند', ['sehat mand', 'sehatmand', 'healthy']],
    ['زخمی', ['zakhmi', 'zakhmee', 'zakhm']],
    ['بہتر', ['behtar', 'behtarr', 'behtareen']],
    ['بدتر', ['badtar', 'baddtar', 'badtareen']],
    ['جدید', ['jadeed', 'jadeedd', 'modern']],
    ['قدیم', ['qadeem', 'qadeemm', 'purana']],
    ['عام', ['aam', 'aamm', 'aam tor par']],
    ['خاص', ['khaas', 'khaass', 'khaas tor par']],
    ['نجی', ['niji', 'private', 'niji sector']],
    ['سرکاری', ['sarkari', 'sarkaari', 'government']],
    ['عدالت', ['adaalat', 'adalat', 'court']],
    ['جج', ['judge', 'jaj', 'judge sahib']],
    ['وکیل', ['wakeel', 'vakeel', 'lawyer']],
    ['پولیس', ['police', 'polees', 'police wala']],
    ['چور', ['chor', 'chorr', 'chori']],
    ['چوری', ['chori', 'choree', 'choriyan']],
    ['سزا', ['saza', 'sazaa', 'sazayen']],
    ['جیل', ['jail', 'jeel', 'jail mein']],
    ['جرمانہ', ['jurmaana', 'jurmana', 'fine']],
    ['ثبوت', ['saboot', 'suboot', 'evidence']],
    ['گواہ', ['gawah', 'gavaah', 'gawahin']],
    ['انصاف', ['insaaf', 'insaf', 'insaaf chahiye']],
    ['ظلم', ['zulm', 'zulmm', 'zulm na karo']],
    ['حق', ['haq', 'haqq', 'haq ada karna']],
    ['فرض', ['farz', 'farzz', 'farz hai']],
    ['ذمہ داری', ['zimmedari', 'zimma daari', 'zimmedari ka']],
    ['اجازت', ['ijazat', 'ejaazat', 'ijazat hai']],
    ['منع', ['mana', 'manaa', 'mana hai']],
    ['قاعدہ', ['qaaida', 'qaedah', 'rules']],
    ['جمہوریت', ['jamhooriat', 'jamhuriyat', 'democracy']],
    ['غلامی', ['ghulaami', 'ghulami', 'slavery']],
    ['سلامتی', ['salamati', 'salmaati', 'aman']],
    ['جنگ', ['jang', 'jangg', 'jung']],
    ['امن', ['aman', 'amann', 'peace']],
    ['معاہدہ', ['muahida', 'muaahida', 'agreement']],
    ['سفارت', ['safaarat', 'safarat', 'embassy']],
    ['سرحد', ['sarhad', 'sarhadd', 'border']],
    ['پاسپورٹ', ['passport', 'paasport', 'pass port']],
    ['ویزا', ['visa', 'veezaa', 'visa lagwana']],
    ['سفر', ['safar', 'safarr', 'safar par']],
    ['ٹکٹ', ['ticket', 'tikkat', 'tickets']],
    ['ہوٹل', ['hotel', 'hoatel', 'hotel mein']],
    ['خیمہ', ['khema', 'kheema', 'camping']],
    ['کمرہ', ['kamra', 'kamrah', 'kamray']],
    ['صابن', ['saabun', 'sabun', 'soap']],
    ['شیمپو', ['shampoo', 'shampo', 'shampoo use']],
    ['ریزر', ['razor', 'rezar', 'razorr']],
    ['بلی', ['billi', 'billee', 'cat']],
    ['کتا', ['kutta', 'kutay', 'dog']],
    ['خرگوش', ['khargosh', 'khargoshh', 'rabbit']],
    ['چوہا', ['chooha', 'chhua', 'mouse']],
    ['بندر', ['bandar', 'bandarr', 'monkey']],
    ['شیر', ['sher', 'sherr', 'lion']],
    ['چیتا', ['cheeta', 'cheetah', 'cheetay']],
    ['ہاتھی', ['haathi', 'hathi', 'elephant']],
    ['سانپ', ['saanp', 'sanp', 'snake']],
    ['مینڈک', ['maindak', 'mendak', 'frog']],
    ['مکڑی', ['makri', 'makdee', 'spider']],
    ['مکھی', ['makhi', 'makkhee', 'fly']],
    ['مچھر', ['machar', 'macharr', 'mosquito']],
    ['کبوتر', ['kabootar', 'kabutar', 'pigeon']],
    ['بط', ['batt', 'duck', 'bat']],
    ['عقاب', ['uqaab', 'ukaab', 'eagle']],
    ['کوّا', ['kauwa', 'kaawwa', 'crow']],
    ['طوطا', ['tota', 'totta', 'parrot']],
    ['مور', ['mor', 'moor', 'peacock']],
    ['لڑکا', ['larka', 'larrka', 'larkey']],
    ['لڑکی', ['larki', 'larkee', 'larkiyan']],
    ['مرد', ['mard', 'mardd', 'aadmi']],
    ['ننھا', ['nanha', 'nannha', 'chota bacha']],
    ['بوڑھا', ['boorha', 'burha', 'boorhay']],
    ['جوان', ['jawan', 'javaan', 'youth']],
    ['سادہ', ['saada', 'sada', 'simple']],
    ['چالاک', ['chaalaak', 'chalak', 'clever']],
    ['بیوقوف', ['bewaqoof', 'bewakoof', 'fool']],
    ['عقلمند', ['aqalmand', 'aql mand', 'wise']],
    ['مہربان', ['meharbaan', 'meherban', 'kind']],
    ['مظلوم', ['mazloom', 'mazluum', 'oppressed']],
    ['ظالم', ['zaalim', 'zalim', 'cruel']],
    ['امین', ['ameen', 'amein', 'honest']],
    ['خائن', ['khaain', 'khain', 'traitor']],
    ['محنتی', ['mehnati', 'mehnatee', 'hardworking']],
    ['کاہل', ['kaahil', 'kahil', 'lazy']],
    ['صابر', ['saabir', 'sabir', 'patient']],
    ['پرسکون', ['pursukoon', 'pur sukoon', 'calm']],
    ['خاموش', ['khaamosh', 'khamosh', 'silent']],
    ['باتونی', ['baatoni', 'batooni', 'talkative']],
    ['دوستانہ', ['dostana', 'dostaana', 'friendly']],
    ['بے خوف', ['be khauf', 'bekhauf', 'fearless']],
    ['بے حس', ['be his', 'behiss', 'numb']],
    ['حساس', ['hasaas', 'hassas', 'sensitive']],
    ['خوفزدہ', ['khauffzada', 'khauf zada', 'scared']],
    ['پرامید', ['poraameed', 'pur umeed', 'hopeful']],
    ['ذاتی', ['zaati', 'zati', 'personal']],
    ['عوامی', ['awaami', 'awami', 'public']],
    ['کتا', ['kutta', 'kutay', 'kutay ka']],
  ];

  for (const [ur, keys] of bulk) add(keys, ur);

  return m;
}

/** Frozen dictionary for Roman → Urdu lookup. */
export const ROMAN_TO_URDU: ReadonlyMap<string, string> = buildMap();

/** Number of dictionary keys (variants included). */
export const ROMAN_TO_URDU_KEY_COUNT: number = ROMAN_TO_URDU.size;
