"use client"

import { useEffect } from "react"
import { UrduMagic, extendDictionary } from "urdumagic"

export default function UrduMagicInit() {
  useEffect(() => {
    const savedLang = (localStorage.getItem("urdumagic-site-lang") || "en") as "en" | "ur" | "roman"

    // Add website-specific missing words directly here
    extendDictionary({
      "missing": "گمشدہ",
      "collector": "جمع کنندہ",
      "words": "الفاظ",
      "users": "صارفین",
      "encountered": "سامنا ہوا",
      "the": "دی",
      "total": "کل",
      "unique": "منفرد",
      "loading": "لوڈنگ",
      "fully": "مکمل طور پر",
      "covering": "احاطہ کرنے والا",
      "website's": "ویب سائٹ کا",
      "right": "صحیح",
      "great": "بہت اچھا",
      "add": "شامل کریں",
      "translate": "ترجمہ کریں",
      "websites": "ویب سائٹس",
      "instantly-offline": "فوری طور پر آف لائن",
      "developer-friendly": "ڈویلپر دوست",
      "easiest": "سب سے آسان",
      "way": "طریقہ",
      "support": "معاونت",
      "any": "کوئی بھی",
      "roman": "رومن",
      "works": "کام کرتا ہے",
      "keys": "کلیدیں",
      "required": "درکار",
      "protected": "محفوظ",
      "theek": "ٹھیک",
      "hai": "ہے",
      "khubsoorat": "خوبصورت",
      "mohabbat": "محبت",
      "core": "بنیادی",
      "entries": "اندراجات",
      "perfect": "بہترین",
      "built": "بنایا گیا",
      "every": "ہر",
      "web": "ویب",
      "saas": "ساس",
      "portals": "پورٹلز",
      "personal": "ذاتی",
      "blogs-urdumagic": "بلاگز اردو میجک",
      "fits": "موزوں ہے",
      "dashboards": "ڈیش بورڈز",
      "localize": "مقامی بنائیں",
      "admin": "ایڈمن",
      "panels": "پینلز",
      "instantly": "فوری طور پر",
      "citizens": "شہریوں",
      "chatbots": "چیٹ بوٹس",
      "respond": "جواب دیں",
      "natively": "مقامی طور پر",
      "platforms": "پلیٹ فارمز",
      "deliver": "فراہم کریں",
      "sell": "فروخت کریں",
      "urdu-speaking": "اردو بولنے والے",
      "markets": "مارکیٹوں",
      "blogs": "بلاگز",
      "publish": "شائع کریں",
      "multilingual": "کثیر لسانی",
      "docs": "دستاویزات",
      "developers": "ڈویلپرز",
      "internal": "اندرونی",
      "tools": "ٹولز",
      "enterprise": "انٹرپرائز",
      "apps": "ایپس",
      "seconds": "سیکنڈوں",
      "package": "پیکج",
      "you're": "آپ ہیں",
      "translating": "ترجمہ کر رہے ہیں",
      "a": "ایک",
      "robust": "مضبوط",
      "5-layer": "5-پرت",
      "routing": "روٹنگ",
      "execution": "عمل درآمد",
      "persistence": "استمرار",
      "ensuring": "یقینی بناتے ہوئے",
      "absolute": "مکمل",
      "stability": "استحکام",
      "predictable": "قابل پیش گوئی",
      "results": "نتائج",
      "massive": "وسیع",
      "proprietary": "ملکیتی",
      "entry": "اندراج",
      "provides": "فراہم کرتا ہے",
      "instant": "فوری",
      "lookups": "تلاشیں",
      "vast": "وسیع",
      "terms": "اصطلاحات",
      "phrases": "فقرات",
      "advanced": "جدید",
      "sanitization": "صفائی",
      "entity": "ہستی",
      "protection": "تحفظ",
      "baked": "شامل",
      "lifecycle": "لائف سائیکل",
      "granular": "تفصیلی",
      "monitoring": "نگرانی",
      "built-in": "بلٹ ان",
      "trackers": "ٹریکرز",
      "provide": "فراہم کریں",
      "detailed": "تفصیلی",
      "timing": "وقت بندی",
      "metrics": "میٹرکس",
      "features": "خصوصیات",
      "everything": "سب کچھ",
      "need": "ضرورت",
      "nothing": "کچھ نہیں",
      "don't": "مت کریں",
      "complete": "مکمل",
      "solution": "حل",
      "plugins": "پلگ انز",
      "services": "خدمات",
      "bills": "بل",
      "feature": "خصوصیت",
      "10k+": "10 ہزار+",
      "whole-site": "پوری سائٹ",
      "community": "کمیونٹی",
      "legal": "قانونی",
      "documentation": "دستاویزات",
      "quickstart": "فوری آغاز",
      "playground": "پلے گراؤنڈ",
      "toggle": "ٹوگل",
      "theme": "تھیم",
      "is": "ہے",
      "now": "اب",
      "available": "دستیاب",
      "to": "سے",
      "your": "آپ کا",
      "website": "ویب سائٹ",
      "into": "میں",
      "urdu": "اردو",
      "secure": "محفوظ",
      "and": "اور",
      "javascript": "جاوا اسکرپٹ",
      "application": "ایپلی کیشن",
      "english": "انگریزی",
      "offline": "آف لائن",
      "first": "پہلا",
      "no": "نہیں",
      "internet": "انٹرنیٹ",
      "library": "لائبریری",
      "dictionary": "لغت",
      "license": "لائسنس",
      "for": "کے لیے",
      "project": "منصوبہ",
      "whether": "چاہے",
      "you": "آپ",
      "ship": "شپ",
      "government": "حکومت",
      "or": "یا",
      "in": "میں",
      "reach": "پہنچ",
      "their": "ان کا",
      "language": "زبان",
      "education": "تعلیم",
      "e-commerce": "ای کامرس",
      "content": "مواد",
      "installation": "انسٹالیشن",
      "up": "اوپر",
      "running": "چل رہا ہے",
      "install": "انسٹال کریں",
      "import": "درآمد کریں",
      "one": "ایک",
      "function": "فنکشن",
      "why": "کیوں",
      "choose": "منتخب کریں",
      "make": "بنائیں",
      "accessible": "قابل رسائی",
      "speakers": "بولنے والے",
      "without": "کے بغیر",
      "complexity": "پیچیدگی",
      "of": "کا",
      "heavy": "بھاری",
      "i18n": "آئی اٹھارہ این",
      "libraries": "لائبریریاں",
      "middleware": "مڈل ویئر",
      "on": "پر",
      "pipeline": "پائپ لائن",
      "cache": "کیشے",
      "production": "پیداوار",
      "engine": "انجن",
      "our": "ہمارا",
      "range": "حد",
      "common": "عام",
      "hardened": "مضبوط",
      "encoding": "انکوڈنگ",
      "prototype": "پروٹوٹائپ",
      "pollution": "آلودگی",
      "are": "ہیں",
      "translation": "ترجمہ",
      "async": "غیر ہم وقتی",
      "stage": "مرحلہ",
      "extra": "اضافی",
      "magic": "میجک",
      "mode": "موڈ",
      "ready": "تیار",
      "site": "سائٹ",
      "join": "شامل ہوں",
      "building": "تعمیر",
      "more": "مزید",
      "inclusive": "جامع",
      "experiences": "تجربات",
      "across": "پار",
      "read": "پڑھیں",
      "view": "دیکھیں",
      "github": "گٹ ہب",
      "empowering": "بااختیار بنانا",
      "build": "تعمیر کریں",
      "worldwide": "دنیا بھر میں",
      "privacy": "رازداری",
      "with": "کے ساتھ",
      "back": "واپس",
      "word": "لفظ",
      "review": "جائزہ لیں",
      "that": "کہ",
      "but": "لیکن",
      "from": "سے"
    })

    // Initialize UrduMagic on the website itself
    const magic = UrduMagic.init({
      defaultLang: savedLang,
      modes: ["en", "ur", "roman"],
      showSwitcher: true,
      strategy: "offline",
      collectMissingWords: true,
      persistMissingWords: true,
      performance: {
        debounceMs: 300,
        cacheTTL: 86400000
      }
    })

    let currentLang = savedLang;

    const handleSwitch = (e: CustomEvent) => {
      const newLang = e.detail?.lang
      if (newLang && newLang !== currentLang) {
        currentLang = newLang;
        localStorage.setItem("urdumagic-site-lang", newLang)
        // Only call library if it didn't originate from here
        magic.switchLang(newLang)
      }
    }

    window.addEventListener("urdumagic-lang-switch", handleSwitch as EventListener)

    return () => {
      window.removeEventListener("urdumagic-lang-switch", handleSwitch as EventListener)
      magic.destroy()
    }
  }, [])

  return null
}
