const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'data', 'english-urdu-dictionary.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newEntries = [
  // ─── PHILOSOPHY & LOGIC (50 entries) ──────────────────────────────────────────
  ['epistemology', { urdu: 'علم الکلام', roman: 'ilm-ul-kalam', category: 'philosophy' }],
  ['metaphysics', { urdu: 'مابعد الطبیعیات', roman: 'mabaad-ul-tabiyaat', category: 'philosophy' }],
  ['ontology', { urdu: 'وجودیت', roman: 'wajoodiyat', category: 'philosophy' }],
  ['ethics', { urdu: 'اخلاقیات', roman: 'akhlaqiyat', category: 'philosophy' }],
  ['aesthetics', { urdu: 'جمالیات', roman: 'jamaliat', category: 'philosophy' }],
  ['logic', { urdu: 'منطق', roman: 'mantiq', category: 'philosophy' }],
  ['syllogism', { urdu: 'قیاس', roman: 'qiyaas', category: 'philosophy' }],
  ['premise', { urdu: 'مقدمہ', roman: 'muqaddama', category: 'philosophy' }],
  ['conclusion', { urdu: 'نتیجہ', roman: 'natija', category: 'philosophy' }],
  ['rationalism', { urdu: 'عقلیت پسندی', roman: 'aqliyat pasandi', category: 'philosophy' }],
  ['empiricism', { urdu: 'تجربیت پسندی', roman: 'tajrabiyat pasandi', category: 'philosophy' }],
  ['skepticism', { urdu: 'تشکیک', roman: 'tashkeek', category: 'philosophy' }],
  ['stoicism', { urdu: 'رواقیت', roman: 'riwaqiyat', category: 'philosophy' }],
  ['existentialism', { urdu: 'وجودیت پسندی', roman: 'wajoodiyat pasandi', category: 'philosophy' }],
  ['nihilism', { urdu: 'عدمیت', roman: 'adamiyat', category: 'philosophy' }],
  ['phenomenology', { urdu: 'مظہریت', roman: 'mazhariyat', category: 'philosophy' }],
  ['dialectics', { urdu: 'جدلیات', roman: 'jadliat', category: 'philosophy' }],
  ['dualism', { urdu: 'ثنویت', roman: 'sanviyat', category: 'philosophy' }],
  ['monism', { urdu: 'وحدت الوجود', roman: 'wahdat-ul-wajood', category: 'philosophy' }],
  ['idealism', { urdu: 'تصوریت', roman: 'tasawuriyat', category: 'philosophy' }],
  ['materialism', { urdu: 'مادیت', roman: 'madiyat', category: 'philosophy' }],
  ['determinism', { urdu: 'جبریت', roman: 'jabriyat', category: 'philosophy' }],
  ['free will', { urdu: 'اختیارِ کلی', roman: 'ikhtiyar-e-kulli', category: 'philosophy' }],
  ['morality', { urdu: 'اخلاق', roman: 'akhlaq', category: 'philosophy' }],
  ['virtue', { urdu: 'نیکی', roman: 'neki', category: 'philosophy' }],
  ['utilitarianism', { urdu: 'افادیت پسندی', roman: 'afadiyat pasandi', category: 'philosophy' }],
  ['deontology', { urdu: 'وظیفہ شناسی', roman: 'wazifa shinasi', category: 'philosophy' }],
  ['categorical imperative', { urdu: 'لازمی حکم', roman: 'lazmi hukum', category: 'philosophy' }],
  ['social contract', { urdu: 'عمرانی معاہدہ', roman: 'umrani muahida', category: 'philosophy' }],
  ['sovereignty', { urdu: 'خود مختاری', roman: 'khud mukhtari', category: 'philosophy' }],
  ['altruism', { urdu: 'ایثار', roman: 'eesar', category: 'philosophy' }],
  ['egoism', { urdu: 'انا پرستی', roman: 'ana parasti', category: 'philosophy' }],
  ['subjectivity', { urdu: 'ذاتیت', roman: 'zaatiyat', category: 'philosophy' }],
  ['objectivity', { urdu: 'معروضیت', roman: 'maroziyat', category: 'philosophy' }],
  ['transcendence', { urdu: 'ماورائیت', roman: 'mawaraiyat', category: 'philosophy' }],
  ['paradox', { urdu: 'تضاد', roman: 'tazaad', category: 'philosophy' }],
  ['fallacy', { urdu: 'مغالطہ', roman: 'mughalata', category: 'philosophy' }],
  ['axiom', { urdu: 'بدیہی حقیقت', roman: 'badihi haqeeqat', category: 'philosophy' }],
  ['dogma', { urdu: 'عقیدہ', roman: 'aqeeda', category: 'philosophy' }],
  ['ideology', { urdu: 'نظریہ', roman: 'nazariya', category: 'philosophy' }],
  ['consciousness', { urdu: 'شعور', roman: 'shaoor', category: 'philosophy' }],
  ['unconscious', { urdu: 'لاشعور', roman: 'lashaoor', category: 'philosophy' }],
  ['subconscious', { urdu: 'تحت الشعور', roman: 'teht-ul-shaoor', category: 'philosophy' }],
  ['intuition', { urdu: 'وجدان', roman: 'wijdaan', category: 'philosophy' }],
  ['enlightenment', { urdu: 'روشن خیالی', roman: 'roshan khayali', category: 'philosophy' }],
  ['hermeneutics', { urdu: 'علم تشریح', roman: 'ilm-e-tashreeh', category: 'philosophy' }],
  ['pluralism', { urdu: 'کثرت پسندی', roman: 'kasrat pasandi', category: 'philosophy' }],
  ['secularism', { urdu: 'لادینیت', roman: 'ladiniyat', category: 'philosophy' }],
  ['pragmatism', { urdu: 'عملیت پسندی', roman: 'amliyat pasandi', category: 'philosophy' }],
  ['humanism', { urdu: 'انسان دوستی', roman: 'insan dosti', category: 'philosophy' }],
  // ─── PSYCHOLOGY & MENTAL HEALTH (60 entries) ──────────────────────────────────
  ['psychology', { urdu: 'نفسیات', roman: 'nafsiyat', category: 'psychology' }],
  ['behavior', { urdu: 'رویہ', roman: 'rawaiya', category: 'psychology' }],
  ['cognition', { urdu: 'ادراک', roman: 'idraak', category: 'psychology' }],
  ['emotion', { urdu: 'جذبہ', roman: 'jazba', category: 'psychology' }],
  ['perception', { urdu: 'ادراکِ حسی', roman: 'idraak-e-hissi', category: 'psychology' }],
  ['motivation', { urdu: 'تحریک', roman: 'tehreek', category: 'psychology' }],
  ['personality', { urdu: 'شخصیت', roman: 'shakhsiyat', category: 'psychology' }],
  ['trauma', { urdu: 'صدمہ', roman: 'sadma', category: 'psychology' }],
  ['anxiety', { urdu: 'تشویش', roman: 'tashweesh', category: 'psychology' }],
  ['depression', { urdu: 'ذہنی دباؤ', roman: 'zehni dabao', category: 'psychology' }],
  ['phobia', { urdu: 'خوف', roman: 'khauf', category: 'psychology' }],
  ['addiction', { urdu: 'نشہ', roman: 'nasha', category: 'psychology' }],
  ['therapy', { urdu: 'علاج', roman: 'ilaaj', category: 'psychology' }],
  ['counseling', { urdu: 'مشاورت', roman: 'mushawarat', category: 'psychology' }],
  ['psychiatrist', { urdu: 'ماہرِ نفسیات', roman: 'mahir-e-nafsiyat', category: 'psychology' }],
  ['neurosis', { urdu: 'اعصابی خلل', roman: 'asabi khalal', category: 'psychology' }],
  ['psychosis', { urdu: 'جنون', roman: 'junoon', category: 'psychology' }],
  ['schizophrenia', { urdu: 'انفصامِ ذہنی', roman: 'infisaam-e-zehni', category: 'psychology' }],
  ['bipolar disorder', { urdu: 'دو قطبی خرابی', roman: 'do qutbi kharabi', category: 'psychology' }],
  ['obsession', { urdu: 'خبط', roman: 'khabt', category: 'psychology' }],
  ['compulsion', { urdu: 'مجبوری', roman: 'majoori', category: 'psychology' }],
  ['introvert', { urdu: 'دروں بیں', roman: 'daroon been', category: 'psychology' }],
  ['extrovert', { urdu: 'بروں بیں', roman: 'baroon been', category: 'psychology' }],
  ['empathy', { urdu: 'ہمدردی', roman: 'hamdardi', category: 'psychology' }],
  ['sympathy', { urdu: 'ہمدردی', roman: 'hamdardi', category: 'psychology' }],
  ['intelligence quotient', { urdu: 'ذہانت کا تناسب', roman: 'zahanat ka tanasub', category: 'psychology' }],
  ['emotional intelligence', { urdu: 'جذباتی ذہانت', roman: 'jazbaati zahanat', category: 'psychology' }],
  ['resilience', { urdu: 'لچک', roman: 'lachak', category: 'psychology' }],
  ['self-esteem', { urdu: 'خود اعتمادی', roman: 'khud aitemadi', category: 'psychology' }],
  ['narcissism', { urdu: 'خود پسندی', roman: 'khud pasandi', category: 'psychology' }],
  ['paranoia', { urdu: 'وہمی خلل', roman: 'wahmi khalal', category: 'psychology' }],
  ['hallucination', { urdu: 'واہمہ', roman: 'wahima', category: 'psychology' }],
  ['delusion', { urdu: 'مغالطہ', roman: 'mughalata', category: 'psychology' }],
  ['repressed memory', { urdu: 'دبی ہوئی یاد', roman: 'dabbi hui yaad', category: 'psychology' }],
  ['cognitive dissonance', { urdu: 'ادراکی تضاد', roman: 'idraaki tazaad', category: 'psychology' }],
  ['classical conditioning', { urdu: 'کلاسیکی مشروطیت', roman: 'classiki mashrootiyat', category: 'psychology' }],
  ['operant conditioning', { urdu: 'عملی مشروطیت', roman: 'amli mashrootiyat', category: 'psychology' }],
  ['reinforcement', { urdu: 'تقویت', roman: 'taqwiyat', category: 'psychology' }],
  ['punishment', { urdu: 'سزا', roman: 'saza', category: 'psychology' }],
  ['sublimation', { urdu: 'تصعید', roman: 'taseed', category: 'psychology' }],
  ['projection', { urdu: 'اسقاط', roman: 'isqaat', category: 'psychology' }],
  ['regression', { urdu: 'رجعت', roman: 'rajat', category: 'psychology' }],
  ['defense mechanism', { urdu: 'دفاعی طریقہ کار', roman: 'difayi tariqa kaar', category: 'psychology' }],
  ['stress management', { urdu: 'ذہنی دباؤ کا انتظام', roman: 'zehni dabao ka intezam', category: 'psychology' }],
  ['mindfulness', { urdu: 'ذہن سازی', roman: 'zehn saazi', category: 'psychology' }],
  ['meditation', { urdu: 'مراقبہ', roman: 'muraqba', category: 'psychology' }],
  ['panic attack', { urdu: 'خوف کا دورہ', roman: 'khauf ka dora', category: 'psychology' }],
  ['insomnia', { urdu: 'بے خوابی', roman: 'be khwaabi', category: 'psychology' }],
  ['hypnosis', { urdu: 'عملِ سموہن', roman: 'amal-e-samohan', category: 'psychology' }],
  ['dream analysis', { urdu: 'خوابوں کا تجزیہ', roman: 'khwabon ka tajzia', category: 'psychology' }],
  ['attachment style', { urdu: 'وابستگی کا انداز', roman: 'wabastagi ka andaz', category: 'psychology' }],
  ['social anxiety', { urdu: 'سماجی تشویش', roman: 'samaji tashweesh', category: 'psychology' }],
  ['identity crisis', { urdu: 'شناخت کا بحران', roman: 'shanakht ka buhran', category: 'psychology' }],
  ['midlife crisis', { urdu: 'ادھیڑ عمری کا بحران', roman: 'adher umri ka buhran', category: 'psychology' }],
  ['peer pressure', { urdu: 'ہم عمروں کا دباؤ', roman: 'hum umron ka dabao', category: 'psychology' }],
  ['groupthink', { urdu: 'گروہی سوچ', roman: 'grohi soch', category: 'psychology' }],
  ['conformity', { urdu: 'مطابقت', roman: 'mutabiqat', category: 'psychology' }],
  ['prejudice', { urdu: 'تعصب', roman: 'taasub', category: 'psychology' }],
  ['discrimination', { urdu: 'امتیاز', roman: 'imtiyaz', category: 'psychology' }],
  ['stereotype', { urdu: 'فرسودہ خیالات', roman: 'farsuda khayalat', category: 'psychology' }],
  // ─── ADVANCED SCIENCE: PHYSICS (35 entries) ──────────────────────────────────
  ['quantum mechanics', { urdu: 'کوانٹم میکانکس', roman: 'quantum mechanics', category: 'physics' }],
  ['relativity', { urdu: 'اضافیت', roman: 'izafiyat', category: 'physics' }],
  ['thermodynamics', { urdu: 'حر حرکیات', roman: 'har harkiayat', category: 'physics' }],
  ['electromagnetism', { urdu: 'برق مقناطیسیت', roman: 'barq maqnateesiyat', category: 'physics' }],
  ['particle physics', { urdu: 'ذراتی طبیعیات', roman: 'zarrati tabiyaat', category: 'physics' }],
  ['astrophysics', { urdu: 'فلکی طبیعیات', roman: 'falaki tabiyaat', category: 'physics' }],
  ['nuclear fusion', { urdu: 'نیوکلیائی انضمام', roman: 'nuclear fusion', category: 'physics' }],
  ['nuclear fission', { urdu: 'نیوکلیائی انشقاق', roman: 'nuclear fission', category: 'physics' }],
  ['entropy', { urdu: 'انتشار', roman: 'intishar', category: 'physics' }],
  ['superconductivity', { urdu: 'اعلی موصلیت', roman: 'aala moosliyat', category: 'physics' }],
  ['photon', { urdu: 'نوریہ', roman: 'nooriya', category: 'physics' }],
  ['electron', { urdu: 'برقیہ', roman: 'barqiya', category: 'physics' }],
  ['neutron', { urdu: 'نیوٹران', roman: 'neutron', category: 'physics' }],
  ['proton', { urdu: 'پروٹون', roman: 'proton', category: 'physics' }],
  ['boson', { urdu: 'بوسون', roman: 'boson', category: 'physics' }],
  ['fermion', { urdu: 'فرمیون', roman: 'fermion', category: 'physics' }],
  ['dark matter', { urdu: 'تاریک مادہ', roman: 'tareek mada', category: 'physics' }],
  ['dark energy', { urdu: 'تاریک توانائی', roman: 'tareek tawanaayi', category: 'physics' }],
  ['black hole', { urdu: 'سیاہ شگاف', roman: 'siyah shigaaf', category: 'physics' }],
  ['wormhole', { urdu: 'ورم ہول', roman: 'wormhole', category: 'physics' }],
  ['singularity', { urdu: 'وحدانیت', roman: 'wahdaniyat', category: 'physics' }],
  ['event horizon', { urdu: 'واقعاتی افق', roman: 'waqiyati ufuq', category: 'physics' }],
  ['big bang', { urdu: 'بگ بینگ', roman: 'big bang', category: 'physics' }],
  ['cosmology', { urdu: 'کونیات', roman: 'kouniyat', category: 'physics' }],
  ['spacetime', { urdu: 'زمان و مکان', roman: 'zaman-o-makan', category: 'physics' }],
  ['gravitation', { urdu: 'کشش ثقل', roman: 'kashish-e-saqal', category: 'physics' }],
  ['momentum', { urdu: 'میعار حرکت', roman: 'miyar-e-harkat', category: 'physics' }],
  ['inertia', { urdu: 'جمود', roman: 'jamood', category: 'physics' }],
  ['centrifugal force', { urdu: 'گریز مرکز قوت', roman: 'guraiz markaz quwat', category: 'physics' }],
  ['centripetal force', { urdu: 'مرکز مائل قوت', roman: 'markaz mayal quwat', category: 'physics' }],
  ['kinetic energy', { urdu: 'حرکی توانائی', roman: 'harki tawanaayi', category: 'physics' }],
  ['potential energy', { urdu: 'مخفی توانائی', roman: 'makhfi tawanaayi', category: 'physics' }],
  ['velocity', { urdu: 'رفتار', roman: 'raftaar', category: 'physics' }],
  ['acceleration', { urdu: 'اسراع', roman: 'isra', category: 'physics' }],
  ['refraction', { urdu: 'انعطاف', roman: 'inataaf', category: 'physics' }],
  // ─── ADVANCED SCIENCE: CHEMISTRY (35 entries) ────────────────────────────────
  ['organic chemistry', { urdu: 'نامیاتی کیمیا', roman: 'namiyati kimiya', category: 'chemistry' }],
  ['inorganic chemistry', { urdu: 'غیر نامیاتی کیمیا', roman: 'ghair namiyati kimiya', category: 'chemistry' }],
  ['biochemistry', { urdu: 'حیاتیاتی کیمیا', roman: 'hayatiyati kimiya', category: 'chemistry' }],
  ['analytical chemistry', { urdu: 'تجزیاتی کیمیا', roman: 'tajziyati kimiya', category: 'chemistry' }],
  ['stoichiometry', { urdu: 'عنصری پیمائش', roman: 'unsuri paimaish', category: 'chemistry' }],
  ['catalyst', { urdu: 'عمل انگیز', roman: 'amal angeez', category: 'chemistry' }],
  ['reaction', { urdu: 'تعامل', roman: 'taamul', category: 'chemistry' }],
  ['enzyme', { urdu: 'خمیرہ', roman: 'khameera', category: 'chemistry' }],
  ['polymer', { urdu: 'پولیمر', roman: 'polymer', category: 'chemistry' }],
  ['monomer', { urdu: 'مونو میر', roman: 'monomer', category: 'chemistry' }],
  ['isomer', { urdu: 'ہم ترکیبی', roman: 'hum tarkeebi', category: 'chemistry' }],
  ['isotope', { urdu: 'ہم جا', roman: 'hum ja', category: 'chemistry' }],
  ['allotropy', { urdu: 'بہروپیت', roman: 'behrupiyat', category: 'chemistry' }],
  ['oxidation', { urdu: 'عملِ تکسید', roman: 'amal-e-takseed', category: 'chemistry' }],
  ['reduction', { urdu: 'عملِ تحویل', roman: 'amal-e-tehweel', category: 'chemistry' }],
  ['electrolysis', { urdu: 'برق پاشیدگی', roman: 'barq pashidagi', category: 'chemistry' }],
  ['valence', { urdu: 'گرفت', roman: 'girift', category: 'chemistry' }],
  ['covalent bond', { urdu: 'اشتراکی گرفت', roman: 'ishtiraaki girift', category: 'chemistry' }],
  ['ionic bond', { urdu: 'آئیونی گرفت', roman: 'ionic girift', category: 'chemistry' }],
  ['solubility', { urdu: 'حل پذیری', roman: 'hal pazeeri', category: 'chemistry' }],
  ['distillation', { urdu: 'عملِ کشید', roman: 'amal-e-kasheed', category: 'chemistry' }],
  ['chromatography', { urdu: 'رنگ نگاری', roman: 'rang nigari', category: 'chemistry' }],
  ['titration', { urdu: 'تتار', roman: 'titaar', category: 'chemistry' }],
  ['molarity', { urdu: 'مولریت', roman: 'molarity', category: 'chemistry' }],
  ['pH scale', { urdu: 'پی ایچ پیمانہ', roman: 'pH paimaish', category: 'chemistry' }],
  ['acidic', { urdu: 'تیزابی', roman: 'tezabi', category: 'chemistry' }],
  ['alkaline', { urdu: 'الکلی', roman: 'alkali', category: 'chemistry' }],
  ['corrosion', { urdu: 'زنگ خوردگی', roman: 'zang khurdagi', category: 'chemistry' }],
  ['hydrocarbon', { urdu: 'ہائیڈرو کاربن', roman: 'hydrocarbon', category: 'chemistry' }],
  ['aromatic', { urdu: 'خوشبودار', roman: 'khushbudar', category: 'chemistry' }],
  ['spectroscopy', { urdu: 'طیف نگاری', roman: 'taif nigari', category: 'chemistry' }],
  ['thermodynamics chemistry', { urdu: 'حر کیمیات', roman: 'har kimiyat', category: 'chemistry' }],
  ['kinetics', { urdu: 'حرکیات', roman: 'harkiayat', category: 'chemistry' }],
  ['equilibrium', { urdu: 'توازن', roman: 'tawazun', category: 'chemistry' }],
  ['precipitate', { urdu: 'رسوب', roman: 'rasoob', category: 'chemistry' }],
  // ─── ADVANCED SCIENCE: BIOLOGY (30 entries) ──────────────────────────────────
  ['genetics', { urdu: 'علمِ وراثت', roman: 'ilm-e-warasat', category: 'biology' }],
  ['genomics', { urdu: 'جینومکس', roman: 'genomics', category: 'biology' }],
  ['proteomics', { urdu: 'پروٹیومکس', roman: 'proteomics', category: 'biology' }],
  ['microbiology', { urdu: 'خرد حیاتیات', roman: 'khurd hayatiyat', category: 'biology' }],
  ['biotechnology', { urdu: 'حیاتیاتی ٹیکنالوجی', roman: 'hayatiyati technology', category: 'biology' }],
  ['evolution', { urdu: 'ارتقاء', roman: 'irtiqa', category: 'biology' }],
  ['natural selection', { urdu: 'قدرتی انتخاب', roman: 'qudrati intikhab', category: 'biology' }],
  ['mutation', { urdu: 'تغیر', roman: 'taghayur', category: 'biology' }],
  ['metabolism', { urdu: 'استحالہ', roman: 'istehala', category: 'biology' }],
  ['photosynthesis', { urdu: 'ضیائی تالیف', roman: 'ziyayi taleef', category: 'biology' }],
  ['respiration', { urdu: 'عملِ تنفس', roman: 'amal-e-tanaffus', category: 'biology' }],
  ['mitosis', { urdu: 'نموئی تقسیم', roman: 'namuyi taqseem', category: 'biology' }],
  ['meiosis', { urdu: 'تخفیفی تقسیم', roman: 'takhfeefi taqseem', category: 'biology' }],
  ['homeostasis', { urdu: 'حیاتیاتی توازن', roman: 'hayatiyati tawazun', category: 'biology' }],
  ['ecosystem', { urdu: 'ماحولیاتی نظام', roman: 'maholiyati nizam', category: 'biology' }],
  ['biodiversity', { urdu: 'حیاتیاتی تنوع', roman: 'hayatiyati tanawu', category: 'biology' }],
  ['taxonomy', { urdu: 'درجہ بندی', roman: 'darja bandi', category: 'biology' }],
  ['embryology', { urdu: 'جنین یات', roman: 'janeeniyat', category: 'biology' }],
  ['immunology', { urdu: 'علمِ مدافعت', roman: 'ilm-e-mudafiat', category: 'biology' }],
  ['neurobiology', { urdu: 'اعصابی حیاتیات', roman: 'asabi hayatiyat', category: 'biology' }],
  ['physiology', { urdu: 'علمِ افعال الاعضاء', roman: 'ilm-e-afaal-ul-aza', category: 'biology' }],
  ['anatomy', { urdu: 'تشریح الاعضاء', roman: 'tashreeh-ul-aza', category: 'biology' }],
  ['endocrinology', { urdu: 'علمِ غدود', roman: 'ilm-e-ghudood', category: 'biology' }],
  ['pathology', { urdu: 'امراضیات', roman: 'amraziyat', category: 'biology' }],
  ['pharmacology', { urdu: 'علم الادویات', roman: 'ilm-ul-adviyat', category: 'biology' }],
  ['virology', { urdu: 'علمِ وائرس', roman: 'ilm-e-virus', category: 'biology' }],
  ['bacteriology', { urdu: 'بیکٹیریا کا علم', roman: 'bacteria ka ilm', category: 'biology' }],
  ['parasitology', { urdu: 'طفیلیات', roman: 'tufailiyat', category: 'biology' }],
  ['oncology', { urdu: 'سرطانیات', roman: 'sartaniyat', category: 'biology' }],
  ['epidemiology', { urdu: 'وبائیات', roman: 'wabaiyat', category: 'biology' }],
  // ─── MODERN WORKPLACE & REMOTE WORK (50 entries) ──────────────────────────────
  ['remote work', { urdu: 'دور دراز کا کام', roman: 'door daraz ka kaam', category: 'workplace' }],
  ['telecommuting', { urdu: 'گھر سے کام', roman: 'ghar se kaam', category: 'workplace' }],
  ['virtual meeting', { urdu: 'ورچوئل میٹنگ', roman: 'virtual meeting', category: 'workplace' }],
  ['video conferencing', { urdu: 'ویڈیو کانفرنسنگ', roman: 'video conferencing', category: 'workplace' }],
  ['asynchronous communication', { urdu: 'غیر ہم وقتی مواصلات', roman: 'ghair hum waqti muwasalat', category: 'workplace' }],
  ['workspace', { urdu: 'کام کی جگہ', roman: 'kaam ki jagah', category: 'workplace' }],
  ['coworking space', { urdu: 'اشتراکی دفتر', roman: 'ishtiraaki daftar', category: 'workplace' }],
  ['work-life balance', { urdu: 'کام اور زندگی کا توازن', roman: 'kaam aur zindagi ka tawazun', category: 'workplace' }],
  ['burnout', { urdu: 'ذہنی تھکن', roman: 'zehni thakan', category: 'workplace' }],
  ['productivity', { urdu: 'پیداواری صلاحیت', roman: 'peidawari salahiyat', category: 'workplace' }],
  ['project management', { urdu: 'منصوبہ بندی', roman: 'mansuba bandi', category: 'workplace' }],
  ['deadline', { urdu: 'آخری تاریخ', roman: 'aakhri tareekh', category: 'workplace' }],
  ['milestone', { urdu: 'سنگ میل', roman: 'sang-e-meel', category: 'workplace' }],
  ['deliverable', { urdu: 'فراہمی کے قابل', roman: 'farahmi kay qaabil', category: 'workplace' }],
  ['stakeholder', { urdu: 'حصہ دار', roman: 'hissa dar', category: 'workplace' }],
  ['onboarding', { urdu: 'بھرتی کا عمل', roman: 'bharti ka amal', category: 'workplace' }],
  ['mentorship', { urdu: 'رہنمائی', roman: 'rehnumayi', category: 'workplace' }],
  ['upskilling', { urdu: 'مہارت میں اضافہ', roman: 'maharat mein izafa', category: 'workplace' }],
  ['reskilling', { urdu: 'نئی مہارتیں سیکھنا', roman: 'nayi maharatein seekhna', category: 'workplace' }],
  ['soft skills', { urdu: 'نرم مہارتیں', roman: 'narm maharatein', category: 'workplace' }],
  ['hard skills', { urdu: 'تکنیکی مہارتیں', roman: 'takneeki maharatein', category: 'workplace' }],
  ['performance review', { urdu: 'کارکردگی کا جائزہ', roman: 'karkardagi ka jaiza', category: 'workplace' }],
  ['feedback', { urdu: 'تاثرات', roman: 'taasurat', category: 'workplace' }],
  ['collaboration tool', { urdu: 'اشتراکی آلہ', roman: 'ishtiraaki aalah', category: 'workplace' }],
  ['cloud storage', { urdu: 'کلاؤڈ اسٹوریج', roman: 'cloud storage', category: 'workplace' }],
  ['data entry', { urdu: 'ڈیٹا انٹری', roman: 'data entry', category: 'workplace' }],
  ['transcription', { urdu: 'نقل نویسی', roman: 'naqal nawesi', category: 'workplace' }],
  ['freelancing', { urdu: 'آزادانہ کام', roman: 'azadana kaam', category: 'workplace' }],
  ['gig economy', { urdu: 'عارضی معیشت', roman: 'aarzi maeeshat', category: 'workplace' }],
  ['digital nomad', { urdu: 'ڈیجیٹل خانہ بدوش', roman: 'digital khana badosh', category: 'workplace' }],
  ['outsourcing', { urdu: 'بیرونی خدمات', roman: 'beruni khidmaat', category: 'workplace' }],
  ['insourcing', { urdu: 'اندرونی خدمات', roman: 'andruni khidmaat', category: 'workplace' }],
  ['supply chain', { urdu: 'سپلائی چین', roman: 'supply chain', category: 'workplace' }],
  ['logistics', { urdu: 'نقل و حمل', roman: 'naqal-o-hamal', category: 'workplace' }],
  ['inventory management', { urdu: 'اسٹاک کا انتظام', roman: 'stock ka intezam', category: 'workplace' }],
  ['quality control', { urdu: 'معیار کی جانچ', roman: 'meyar ki jaanch', category: 'workplace' }],
  ['standard operating procedure', { urdu: 'معیاری طریقہ کار', roman: 'meyari tariqa kaar', category: 'workplace' }],
  ['corporate social responsibility', { urdu: 'کارپوریٹ سماجی ذمہ داری', roman: 'corporate samaji zimadari', category: 'workplace' }],
  ['sustainability report', { urdu: 'پائیداری کی رپورٹ', roman: 'paidari ki report', category: 'workplace' }],
  ['office culture', { urdu: 'دفتر کی ثقافت', roman: 'daftar ki saqafat', category: 'workplace' }],
  ['networking', { urdu: 'روابط بنانا', roman: 'rawabit banana', category: 'workplace' }],
  ['elevator pitch', { urdu: 'مختصر تعارف', roman: 'mukhtasar taaruf', category: 'workplace' }],
  ['business development', { urdu: 'کاروباری ترقی', roman: 'karobari taraqqi', category: 'workplace' }],
  ['market research', { urdu: 'مارکیٹ کی تحقیق', roman: 'market ki tehqeeq', category: 'workplace' }],
  ['target audience', { urdu: 'نشانی سامعین', roman: 'nishani samayeen', category: 'workplace' }],
  ['brand identity', { urdu: 'برانڈ کی شناخت', roman: 'brand ki shanakht', category: 'workplace' }],
  ['customer experience', { urdu: 'صارف کا تجربہ', roman: 'sarif ka tajurba', category: 'workplace' }],
  ['user interface', { urdu: 'صارف کا انٹرفیس', roman: 'user interface', category: 'workplace' }],
  ['user experience', { urdu: 'صارف کا تجربہ', roman: 'user experience', category: 'workplace' }],
  ['agile methodology', { urdu: 'تیز رفتار طریقہ کار', roman: 'tez raftar tariqa kaar', category: 'workplace' }],
  // ─── SOCIAL MEDIA & CONTENT CREATION (50 entries) ─────────────────────────────
  ['influencer', { urdu: 'اثر و رسوخ رکھنے والا', roman: 'asar-o-rusookh rakhne wala', category: 'social_media' }],
  ['content creator', { urdu: 'مواد تخلیق کار', roman: 'mawad takhleeq kaar', category: 'social_media' }],
  ['vlogging', { urdu: 'وی لاگنگ', roman: 'vlogging', category: 'social_media' }],
  ['podcasting', { urdu: 'پوڈ کاسٹنگ', roman: 'podcasting', category: 'social_media' }],
  ['live streaming', { urdu: 'براہ راست نشریات', roman: 'baraah-e-raast nashriyat', category: 'social_media' }],
  ['viral content', { urdu: 'وائرل مواد', roman: 'viral mawad', category: 'social_media' }],
  ['clickbait', { urdu: 'کلک بیت', roman: 'clickbait', category: 'social_media' }],
  ['thumbnail', { urdu: 'تھمب نیل', roman: 'thumbnail', category: 'social_media' }],
  ['algorithm', { urdu: 'الگورتھم', roman: 'algorithm', category: 'social_media' }],
  ['engagement rate', { urdu: 'شمولیت کی شرح', roman: 'shumooliyat ki sharah', category: 'social_media' }],
  ['reach', { urdu: 'پہنچ', roman: 'pahunach', category: 'social_media' }],
  ['impressions', { urdu: 'تاثرات', roman: 'taasurat', category: 'social_media' }],
  ['analytics', { urdu: 'تجزیات', roman: 'tajziyat', category: 'social_media' }],
  ['monetization', { urdu: 'آمدنی بنانا', roman: 'aamdani banana', category: 'social_media' }],
  ['sponsorship', { urdu: 'کفالت', roman: 'kifalat', category: 'social_media' }],
  ['affiliate marketing', { urdu: 'ملحقہ مارکیٹنگ', roman: 'mulhaqa marketing', category: 'social_media' }],
  ['brand deal', { urdu: 'برانڈ کا معاہدہ', roman: 'brand ka muahida', category: 'social_media' }],
  ['community management', { urdu: 'برادری کا انتظام', roman: 'baraadri ka intezam', category: 'social_media' }],
  ['moderation', { urdu: 'اعتدال پسندی', roman: 'aitadaal pasandi', category: 'social_media' }],
  ['trolling', { urdu: 'ٹرولنگ', roman: 'trolling', category: 'social_media' }],
  ['cyberbullying', { urdu: 'سائبر دھونس', roman: 'cyber dhons', category: 'social_media' }],
  ['cancel culture', { urdu: 'منسوخی کی ثقافت', roman: 'mansookhi ki saqafat', category: 'social_media' }],
  ['echo chamber', { urdu: 'گونج دار حجرہ', roman: 'goonj dar hujra', category: 'social_media' }],
  ['fake news', { urdu: 'جعلی خبریں', roman: 'jaali khabrein', category: 'social_media' }],
  ['disinformation', { urdu: 'غلط معلومات', roman: 'ghalat maloomat', category: 'social_media' }],
  ['misinformation', { urdu: 'گمراہ کن معلومات', roman: 'gumrah kun maloomat', category: 'social_media' }],
  ['fact checking', { urdu: 'حقائق کی جانچ', roman: 'haqaiq ki jaanch', category: 'social_media' }],
  ['verified account', { urdu: 'تصدیق شدہ اکاؤنٹ', roman: 'tasdeeq shudah account', category: 'social_media' }],
  ['handle', { urdu: 'ہینڈل', roman: 'handle', category: 'social_media' }],
  ['bio', { urdu: 'تعارف', roman: 'taaruf', category: 'social_media' }],
  ['caption', { urdu: 'عنوان', roman: 'unwan', category: 'social_media' }],
  ['geotag', { urdu: 'جغرافیائی ٹیگ', roman: 'joghrafiyai tag', category: 'social_media' }],
  ['story highlights', { urdu: 'کہانی کی جھلکیاں', roman: 'kahani ki jhalakiyan', category: 'social_media' }],
  ['reels', { urdu: 'ریلز', roman: 'reels', category: 'social_media' }],
  ['shorts', { urdu: 'شارٹس', roman: 'shorts', category: 'social_media' }],
  ['carousel post', { urdu: 'کیروسل پوسٹ', roman: 'carousel post', category: 'social_media' }],
  ['direct message', { urdu: 'براہ راست پیغام', roman: 'baraah-e-raast paigham', category: 'social_media' }],
  ['notifications', { urdu: 'اطلاعات', roman: 'ittilaat', category: 'social_media' }],
  ['privacy settings', { urdu: 'رازداری کی ترتیبات', roman: 'raazdaari ki tarteebat', category: 'social_media' }],
  ['two factor authentication', { urdu: 'دوہری تصدیق', roman: 'dohri tasdeeq', category: 'social_media' }],
  ['blocking', { urdu: 'بلاک کرنا', roman: 'blocking', category: 'social_media' }],
  ['reporting', { urdu: 'رپورٹ کرنا', roman: 'reporting', category: 'social_media' }],
  ['spam', { urdu: 'فضول مواد', roman: 'fazool mawad', category: 'social_media' }],
  ['bot', { urdu: 'بوٹ', roman: 'bot', category: 'social_media' }],
  ['follower count', { urdu: 'پیروکاروں کی تعداد', roman: 'perokaaron ki tadaad', category: 'social_media' }],
  ['trending topic', { urdu: 'مقبول موضوع', roman: 'maqbool mozu', category: 'social_media' }],
  ['niche', { urdu: 'مخصوص شعبہ', roman: 'makhsoos shoba', category: 'social_media' }],
  ['engagement', { urdu: 'شمولیت', roman: 'shumooliyat', category: 'social_media' }],
  ['organic reach', { urdu: 'قدرتی پہنچ', roman: 'qudrati pahunach', category: 'social_media' }],
  ['paid promotion', { urdu: 'ادائیگی والی تشہیر', roman: 'adaigi wali tashheer', category: 'social_media' }],
  // ─── HUMAN RIGHTS & SOCIAL JUSTICE (50 entries) ──────────────────────────────
  ['human rights', { urdu: 'انسانی حقوق', roman: 'insani huqooq', category: 'social_justice' }],
  ['civil liberties', { urdu: 'شہری آزادیاں', roman: 'shahri azadiyan', category: 'social_justice' }],
  ['equality', { urdu: 'مساوات', roman: 'masawat', category: 'social_justice' }],
  ['equity', { urdu: 'عدل و انصاف', roman: 'adl-o-insaf', category: 'social_justice' }],
  ['justice', { urdu: 'انصاف', roman: 'insaf', category: 'social_justice' }],
  ['freedom of speech', { urdu: 'آزادی اظہار', roman: 'azadi-e-izhaar', category: 'social_justice' }],
  ['freedom of religion', { urdu: 'مذہبی آزادی', roman: 'mazhabi azadi', category: 'social_justice' }],
  ['right to education', { urdu: 'تعلیم کا حق', roman: 'taleem ka haq', category: 'social_justice' }],
  ['right to health', { urdu: 'صحت کا حق', roman: 'sehat ka haq', category: 'social_justice' }],
  ['right to vote', { urdu: 'ووٹ کا حق', roman: 'vote ka haq', category: 'social_justice' }],
  ['democracy', { urdu: 'جمہوریت', roman: 'jamhooriyat', category: 'social_justice' }],
  ['rule of law', { urdu: 'قانون کی حکمرانی', roman: 'qanoon ki hukmarani', category: 'social_justice' }],
  ['due process', { urdu: 'قانونی چارہ جوئی', roman: 'qanooni chara joyi', category: 'social_justice' }],
  ['social justice', { urdu: 'سماجی انصاف', roman: 'samaji insaf', category: 'social_justice' }],
  ['activism', { urdu: 'سرگرمی', roman: 'sargarmi', category: 'social_justice' }],
  ['protest', { urdu: 'احتجاج', roman: 'ihtijaj', category: 'social_justice' }],
  ['demonstration', { urdu: 'مظاہرہ', roman: 'muzahira', category: 'social_justice' }],
  ['petition', { urdu: 'درخواست', roman: 'darkhwast', category: 'social_justice' }],
  ['advocacy', { urdu: 'وکالت', roman: 'wakalat', category: 'social_justice' }],
  ['non-governmental organization', { urdu: 'غیر سرکاری تنظیم', roman: 'ghair sarkari tanzeem', category: 'social_justice' }],
  ['humanitarian aid', { urdu: 'انسانی ہمدردی کی امداد', roman: 'insani hamdardi ki imdad', category: 'social_justice' }],
  ['refugee', { urdu: 'پناہ گزین', roman: 'panah guzeen', category: 'social_justice' }],
  ['asylum', { urdu: 'پناہ', roman: 'panah', category: 'social_justice' }],
  ['migration', { urdu: 'ہجرت', roman: 'hijrat', category: 'social_justice' }],
  ['human trafficking', { urdu: 'انسانی اسمگلنگ', roman: 'insani smuggling', category: 'social_justice' }],
  ['forced labor', { urdu: 'جبری مشقت', roman: 'jabri mushaqqat', category: 'social_justice' }],
  ['child labor', { urdu: 'بچوں سے مزدوری', roman: 'bachon se mazduri', category: 'social_justice' }],
  ['gender equality', { urdu: 'صنف کی مساوات', roman: 'sinf ki masawat', category: 'social_justice' }],
  ['women rights', { urdu: 'خواتین کے حقوق', roman: 'khawateen kay huqooq', category: 'social_justice' }],
  ['minority rights', { urdu: 'اقلیتوں کے حقوق', roman: 'aqliyatun kay huqooq', category: 'social_justice' }],
  ['indigenous people', { urdu: 'مقامی لوگ', roman: 'muqaami log', category: 'social_justice' }],
  ['discrimination justice', { urdu: 'امتیاز کے خلاف انصاف', roman: 'imtiyaz kay khilaf insaf', category: 'social_justice' }],
  ['racism', { urdu: 'نسل پرستی', roman: 'nasal parasti', category: 'social_justice' }],
  ['xenophobia', { urdu: 'اجنبیوں سے خوف', roman: 'ajnabiyon se khauf', category: 'social_justice' }],
  ['marginalization', { urdu: 'حاشیہ برداری', roman: 'hashiya bardari', category: 'social_justice' }],
  ['empowerment', { urdu: 'اختیار دہی', roman: 'ikhtiyar dehi', category: 'social_justice' }],
  ['inclusion', { urdu: 'شمولیت', roman: 'shumooliyat', category: 'social_justice' }],
  ['diversity', { urdu: 'تنوع', roman: 'tanawu', category: 'social_justice' }],
  ['tolerance', { urdu: 'رواداری', roman: 'rawadari', category: 'social_justice' }],
  ['peacekeeping', { urdu: 'امن قائم رکھنا', roman: 'aman qaim rakhna', category: 'social_justice' }],
  ['conflict resolution', { urdu: 'تنازعات کا حل', roman: 'tanazaat ka hal', category: 'social_justice' }],
  ['amnesty', { urdu: 'عام معافی', roman: 'aam maafi', category: 'social_justice' }],
  ['war crimes', { urdu: 'جنگی جرائم', roman: 'jangi jaraim', category: 'social_justice' }],
  ['genocide', { urdu: 'نسل کشی', roman: 'nasal kushi', category: 'social_justice' }],
  ['torture', { urdu: 'تشدد', roman: 'tashaddud', category: 'social_justice' }],
  ['arbitrary detention', { urdu: 'من مانی حراست', roman: 'man mani hirasat', category: 'social_justice' }],
  ['habeas corpus', { urdu: 'حکمِ رہائی', roman: 'hukum-e-rehayi', category: 'social_justice' }],
  ['universal declaration', { urdu: 'عالمی اعلامیہ', roman: 'alami elamiya', category: 'social_justice' }],
  ['social welfare', { urdu: 'سماجی بہبود', roman: 'samaji behbud', category: 'social_justice' }],
  ['poverty alleviation', { urdu: 'غربت کا خاتمہ', roman: 'ghurbat ka khatima', category: 'social_justice' }],
  // ─── ENVIRONMENTAL SCIENCE & SUSTAINABILITY (50 entries) ──────────────────────
  ['global warming', { urdu: 'عالمی حدت', roman: 'alami hiddat', category: 'environment' }],
  ['climate change', { urdu: 'ماحول کی تبدیلی', roman: 'mahol ki tabdeeli', category: 'environment' }],
  ['greenhouse effect', { urdu: 'سبز مکانی اثر', roman: 'sabz makani asar', category: 'environment' }],
  ['carbon footprint', { urdu: 'کاربن کا اثر', roman: 'carbon ka asar', category: 'environment' }],
  ['renewable energy', { urdu: 'قابل تجدید توانائی', roman: 'qabil-e-tajdeed tawanaayi', category: 'environment' }],
  ['solar power', { urdu: 'شمسی توانائی', roman: 'shamsi tawanaayi', category: 'environment' }],
  ['wind energy', { urdu: 'ہوائی توانائی', roman: 'hawai tawanaayi', category: 'environment' }],
  ['hydroelectric power', { urdu: 'پن بجلی', roman: 'pan bijli', category: 'environment' }],
  ['geothermal energy', { urdu: 'ارضی حرارتی توانائی', roman: 'arzi hararti tawanaayi', category: 'environment' }],
  ['biomass energy', { urdu: 'حیاتیاتی توانائی', roman: 'hayatiyati tawanaayi', category: 'environment' }],
  ['sustainability', { urdu: 'پائیداری', roman: 'paidari', category: 'environment' }],
  ['conservation', { urdu: 'تحفظ', roman: 'tahaffuz', category: 'environment' }],
  ['biodiversity conservation', { urdu: 'حیاتیاتی تنوع کا تحفظ', roman: 'hayatiyati tanawu ka tahaffuz', category: 'environment' }],
  ['deforestation', { urdu: 'جنگلات کا کٹاؤ', roman: 'janglaat ka katao', category: 'environment' }],
  ['reforestation', { urdu: 'شجر کاری', roman: 'shajar kari', category: 'environment' }],
  ['afforestation', { urdu: 'نئے جنگلات اگانا', roman: 'naye janglaat ugana', category: 'environment' }],
  ['pollution', { urdu: 'آلودگی', roman: 'aloodgi', category: 'environment' }],
  ['air quality index', { urdu: 'ہوا کے معیار کا انڈیکس', roman: 'hawa kay meyar ka index', category: 'environment' }],
  ['water scarcity', { urdu: 'پانی کی قلت', roman: 'paani ki qillat', category: 'environment' }],
  ['ocean acidification', { urdu: 'سمندر کی تیزابیت', roman: 'samundar ki tezabiyat', category: 'environment' }],
  ['waste management', { urdu: 'کچرے کا انتظام', roman: 'kachray ka intezam', category: 'environment' }],
  ['recycling', { urdu: 'دوبارہ استعمال', roman: 'dobara istemal', category: 'environment' }],
  ['upcycling', { urdu: 'تخلیقی دوبارہ استعمال', roman: 'takhliqi dobara istemal', category: 'environment' }],
  ['composting', { urdu: 'نامیاتی کھاد بنانا', roman: 'namiyati khaad banana', category: 'environment' }],
  ['hazardous waste', { urdu: 'خطرناک فضلہ', roman: 'khatarnak fuzla', category: 'environment' }],
  ['ecosystem services', { urdu: 'ماحولیاتی خدمات', roman: 'maholiyati khidmaat', category: 'environment' }],
  ['wildlife protection', { urdu: 'جنگلی حیات کا تحفظ', roman: 'jangli hayat ka tahaffuz', category: 'environment' }],
  ['endangered species', { urdu: 'خطرے میں گھری انواع', roman: 'khatray mein ghiri anwa', category: 'environment' }],
  ['habitat loss', { urdu: 'مسکن کا نقصان', roman: 'maskan ka nuqsan', category: 'environment' }],
  ['invasive species', { urdu: 'تجاوز کرنے والی انواع', roman: 'tajawuz karne wali anwa', category: 'environment' }],
  ['ozone layer', { urdu: 'اوزون کی تہہ', roman: 'ozone ki teh', category: 'environment' }],
  ['acid rain', { urdu: 'تیزابی بارش', roman: 'tezabi barish', category: 'environment' }],
  ['sustainable development', { urdu: 'پائیدار ترقی', roman: 'paidar taraqqi', category: 'environment' }],
  ['eco-friendly', { urdu: 'ماحول دوست', roman: 'mahol dost', category: 'environment' }],
  ['biodegradable', { urdu: 'حیاتیاتی طور پر گلنے والا', roman: 'hayatiyati tor par gulne wala', category: 'environment' }],
  ['zero waste', { urdu: 'صفر فضلہ', roman: 'sifar fuzla', category: 'environment' }],
  ['circular economy', { urdu: 'دائروی معیشت', roman: 'dairvi maeeshat', category: 'environment' }],
  ['energy efficiency', { urdu: 'توانائی کی بچت', roman: 'tawanaayi ki bachat', category: 'environment' }],
  ['carbon capture', { urdu: 'کاربن کا حصول', roman: 'carbon ka husool', category: 'environment' }],
  ['emissions trading', { urdu: 'اخراج کی تجارت', roman: 'ikhraaj ki tijaarat', category: 'environment' }],
  ['environmental impact assessment', { urdu: 'ماحولیاتی اثرات کا اندازہ', roman: 'maholiyati asraat ka andaza', category: 'environment' }],
  ['permafrost melting', { urdu: 'دائمی برف کا پگھلنا', roman: 'daimi barf ka pighalna', category: 'environment' }],
  ['glacier retreat', { urdu: 'گلیشیئر کا پیچھے ہٹنا', roman: 'glacier ka peeche hatna', category: 'environment' }],
  ['sea level rise', { urdu: 'سمندر کی سطح میں اضافہ', roman: 'samundar ki satah mein izafa', category: 'environment' }],
  ['drought', { urdu: 'قحط سالی', roman: 'qahet saali', category: 'environment' }],
  ['flood management', { urdu: 'سیلاب کا انتظام', roman: 'seilaab ka intezam', category: 'environment' }],
  ['soil erosion', { urdu: 'مٹی کا کٹاؤ', roman: 'matti ka katao', category: 'environment' }],
  ['desertification', { urdu: 'صحرا بندی', roman: 'sehra bandi', category: 'environment' }],
  ['overfishing', { urdu: 'ضرورت سے زیادہ ماہی گیری', roman: 'zaroorat se zyada mahi geeri', category: 'environment' }],
  ['urban sprawl', { urdu: 'شہری پھیلاؤ', roman: 'shahri phelao', category: 'environment' }],
  // ─── DIGITAL MARKETING & E-COMMERCE (50 entries) ──────────────────────────────
  ['search engine optimization', { urdu: 'سرچ انجن آپٹیمائزیشن', roman: 'search engine optimization', category: 'marketing' }],
  ['search engine marketing', { urdu: 'سرچ انجن مارکیٹنگ', roman: 'search engine marketing', category: 'marketing' }],
  ['pay per click', { urdu: 'فی کلک ادائیگی', roman: 'fi click adaigi', category: 'marketing' }],
  ['content marketing', { urdu: 'مواد کی مارکیٹنگ', roman: 'mawad ki marketing', category: 'marketing' }],
  ['email marketing', { urdu: 'ای میل مارکیٹنگ', roman: 'email marketing', category: 'marketing' }],
  ['social media marketing', { urdu: 'سوشل میڈیا مارکیٹنگ', roman: 'social media marketing', category: 'marketing' }],
  ['affiliate marketing eCommerce', { urdu: 'الحاقی مارکیٹنگ', roman: 'ilhaqi marketing', category: 'marketing' }],
  ['lead generation', { urdu: 'امیدواروں کی تلاش', roman: 'umeedwaron ki talash', category: 'marketing' }],
  ['conversion rate optimization', { urdu: 'تبدیلی کی شرح میں بہتری', roman: 'tabdeeli ki sharah mein behtari', category: 'marketing' }],
  ['user acquisition', { urdu: 'صارفین کا حصول', roman: 'sarifeen ka husool', category: 'marketing' }],
  ['customer retention', { urdu: 'صارفین کو برقرار رکھنا', roman: 'sarifeen ko barqarar rakhna', category: 'marketing' }],
  ['brand awareness', { urdu: 'برانڈ کی آگاہی', roman: 'brand ki aagahi', category: 'marketing' }],
  ['market segmentation', { urdu: 'مارکیٹ کی تقسیم', roman: 'market ki taqseem', category: 'marketing' }],
  ['demographics', { urdu: 'آبادیاتی خصوصیات', roman: 'abadiyati khusoosiyat', category: 'marketing' }],
  ['psychographics', { urdu: 'نفسیاتی خصوصیات', roman: 'nafsiyati khusoosiyat', category: 'marketing' }],
  ['sales funnel', { urdu: 'فروخت کا عمل', roman: 'farokht ka amal', category: 'marketing' }],
  ['return on investment', { urdu: 'سرمایہ کاری پر منافع', roman: 'sarmaya kari par munafa', category: 'marketing' }],
  ['key performance indicator', { urdu: 'کارکردگی کا کلیدی اشارہ', roman: 'karkardagi ka kaleedi ishara', category: 'marketing' }],
  ['bounce rate', { urdu: 'واپسی کی شرح', roman: 'wapsi ki sharah', category: 'marketing' }],
  ['landing page', { urdu: 'لینڈنگ پیج', roman: 'landing page', category: 'marketing' }],
  ['call to action button', { urdu: 'عمل کا بٹن', roman: 'amal ka button', category: 'marketing' }],
  ['A/B testing', { urdu: 'اے بی ٹیسٹنگ', roman: 'A/B testing', category: 'marketing' }],
  ['customer journey', { urdu: 'صارف کا سفر', roman: 'sarif ka safar', category: 'marketing' }],
  ['omnichannel marketing', { urdu: 'ہمہ جہت مارکیٹنگ', roman: 'hama jehat marketing', category: 'marketing' }],
  ['e-commerce platform', { urdu: 'ای کامرس پلیٹ فارم', roman: 'e-commerce platform', category: 'marketing' }],
  ['shopping cart', { urdu: 'خریداری کی ٹوکری', roman: 'khareedari ki tokri', category: 'marketing' }],
  ['checkout process', { urdu: 'چیک آؤٹ کا عمل', roman: 'checkout ka amal', category: 'marketing' }],
  ['payment gateway', { urdu: 'ادائیگی کا راستہ', roman: 'adaigi ka rasta', category: 'marketing' }],
  ['shipping and handling', { urdu: 'ترسیل اور انتظام', roman: 'tarseel aur intezam', category: 'marketing' }],
  ['order fulfillment', { urdu: 'آرڈر کی تکمیل', roman: 'order ki takmeel', category: 'marketing' }],
  ['dropshipping', { urdu: 'ڈراپ شپنگ', roman: 'dropshipping', category: 'marketing' }],
  ['inventory turnover', { urdu: 'اسٹاک کی گردش', roman: 'stock ki gardish', category: 'marketing' }],
  ['customer lifetime value', { urdu: 'صارف کی زندگی بھر کی قدر', roman: 'sarif ki zindagi bhar ki qadar', category: 'marketing' }],
  ['churn rate', { urdu: 'صارفین کی کمی کی شرح', roman: 'sarifeen ki kami ki sharah', category: 'marketing' }],
  ['marketplace marketing', { urdu: 'منڈی', roman: 'mandi', category: 'marketing' }],
  ['subscription model', { urdu: 'رکنیت کا ماڈل', roman: 'ruknight ka model', category: 'marketing' }],
  ['freemium', { urdu: 'فریمیم', roman: 'freemium', category: 'marketing' }],
  ['upselling', { urdu: 'اضافی فروخت', roman: 'izafi farokht', category: 'marketing' }],
  ['cross-selling', { urdu: 'متعلقہ فروخت', roman: 'mutaalqa farokht', category: 'marketing' }],
  ['digital advertising', { urdu: 'ڈیجیٹل اشتہارات', roman: 'digital ishtiharat', category: 'marketing' }],
  ['programmatic advertising', { urdu: 'پروگراماتی تشہیر', roman: 'programmatic tashheer', category: 'marketing' }],
  ['native advertising', { urdu: 'فطری تشہیر', roman: 'fitri tashheer', category: 'marketing' }],
  ['influencer marketing ecommerce', { urdu: 'اثر و رسوخ رکھنے والوں کی مارکیٹنگ', roman: 'influencer marketing', category: 'marketing' }],
  ['video marketing', { urdu: 'ویڈیو مارکیٹنگ', roman: 'video marketing', category: 'marketing' }],
  ['mobile marketing', { urdu: 'موبائل مارکیٹنگ', roman: 'mobile marketing', category: 'marketing' }],
  ['local SEO', { urdu: 'مقامی ایس ای او', roman: 'local SEO', category: 'marketing' }],
  ['voice search optimization', { urdu: 'صوتی تلاش کی بہتری', roman: 'souti talash ki behtari', category: 'marketing' }],
  ['chatbot', { urdu: 'چیٹ بوٹ', roman: 'chatbot', category: 'marketing' }],
  ['customer relationship management', { urdu: 'صارفین سے تعلقات کا انتظام', roman: 'sarifeen se tuluqat ka intezam', category: 'marketing' }],
  ['marketing automation', { urdu: 'مارکیٹنگ کی خودکاری', roman: 'marketing ki khudkaari', category: 'marketing' }],
  // ─── SPACE EXPLORATION & ASTRONOMY (50 entries) ───────────────────────────────
  ['astronomy', { urdu: 'علمِ فلکیات', roman: 'ilm-e-falkiyat', category: 'space' }],
  ['astrophysics space', { urdu: 'فلکی طبیعیات', roman: 'falaki tabiyaat', category: 'space' }],
  ['cosmology space', { urdu: 'کونیات', roman: 'kouniyat', category: 'space' }],
  ['observatory', { urdu: 'رصد گاہ', roman: 'rasad gah', category: 'space' }],
  ['telescope', { urdu: 'دوربین', roman: 'doorbeen', category: 'space' }],
  ['radio telescope', { urdu: 'ریڈیو دوربین', roman: 'radio doorbeen', category: 'space' }],
  ['space station', { urdu: 'خلائی اسٹیشن', roman: 'khalayi station', category: 'space' }],
  ['satellite', { urdu: 'مصنوعی سیارہ', roman: 'masnooyi sayyara', category: 'space' }],
  ['rocket launch', { urdu: 'راکٹ کی لانچ', roman: 'rocket ki launch', category: 'space' }],
  ['space shuttle', { urdu: 'خلائی شٹل', roman: 'khalayi shuttle', category: 'space' }],
  ['astronaut', { urdu: 'خلاباز', roman: 'khalabaaz', category: 'space' }],
  ['cosmonaut', { urdu: 'روسی خلاباز', roman: 'roosi khalabaaz', category: 'space' }],
  ['mission control', { urdu: 'مشن کنٹرول', roman: 'mission control', category: 'space' }],
  ['space probe', { urdu: 'خلائی تحقیقاتی آلہ', roman: 'khalayi tehqeeqi aalah', category: 'space' }],
  ['rover', { urdu: 'روور', roman: 'rover', category: 'space' }],
  ['lander', { urdu: 'لینڈر', roman: 'lander', category: 'space' }],
  ['orbiter', { urdu: 'آربیٹر', roman: 'orbiter', category: 'space' }],
  ['gravity assist', { urdu: 'کششِ ثقل کی مدد', roman: 'gravity assist', category: 'space' }],
  ['re-entry', { urdu: 'دوبارہ داخلہ', roman: 'dobara dakhla', category: 'space' }],
  ['spacewalk', { urdu: 'خلا میں چہل قدمی', roman: 'khala mein chehal qadmi', category: 'space' }],
  ['microgravity', { urdu: 'خرد ثقل', roman: 'khurd saqal', category: 'space' }],
  ['solar system', { urdu: 'نظام شمسی', roman: 'nizam-e-shamsi', category: 'space' }],
  ['galaxy', { urdu: 'کہکشاں', roman: 'kehkashan', category: 'space' }],
  ['milky way', { urdu: 'کہکشاں', roman: 'kehkashan', category: 'space' }],
  ['andromeda', { urdu: 'اینڈرومیڈا کہکشاں', roman: 'andromeda kehkashan', category: 'space' }],
  ['nebula', { urdu: 'سحابیہ', roman: 'sahabiya', category: 'space' }],
  ['supernova', { urdu: 'سپر نووا', roman: 'supernova', category: 'space' }],
  ['pulsar', { urdu: 'پلسر', roman: 'pulsar', category: 'space' }],
  ['quasar', { urdu: 'کوازار', roman: 'quasar', category: 'space' }],
  ['constellation', { urdu: 'جھرمٹ', roman: 'jhurmat', category: 'space' }],
  ['light year', { urdu: 'نوری سال', roman: 'noori saal', category: 'space' }],
  ['parsec', { urdu: 'پارسیک', roman: 'parsec', category: 'space' }],
  ['magnitude', { urdu: 'قدروقیمت', roman: 'qadroqimat', category: 'space' }],
  ['exoplanet', { urdu: 'بیرونی سیارہ', roman: 'beruni sayyara', category: 'space' }],
  ['habitable zone', { urdu: 'رہائش کے قابل زون', roman: 'rehaish kay qaabil zone', category: 'space' }],
  ['asteroid belt', { urdu: 'سیارچوں کی پٹی', roman: 'sayyarchon ki patti', category: 'space' }],
  ['comet tail', { urdu: 'دوم دار ستارے کی دم', roman: 'doom dar sitaray ki dum', category: 'space' }],
  ['meteor shower', { urdu: 'شہاب ثاقب کی بارش', roman: 'shahab-e-saqib ki barish', category: 'space' }],
  ['black hole event horizon', { urdu: 'سیاہ شگاف کا واقعاتی افق', roman: 'black hole event horizon', category: 'space' }],
  ['wormhole space', { urdu: 'ورم ہول', roman: 'wormhole', category: 'space' }],
  ['dark matter space', { urdu: 'تاریک مادہ', roman: 'tareek mada', category: 'space' }],
  ['dark energy space', { urdu: 'تاریک توانائی', roman: 'tareek tawanaayi', category: 'space' }],
  ['big bang theory', { urdu: 'نظریہ بگ بینگ', roman: 'nazariya big bang', category: 'space' }],
  ['cosmic microwave background', { urdu: 'کائناتی پس منظر کی شعاعیں', roman: 'cosmic microwave background', category: 'space' }],
  ['multiverse', { urdu: 'کثیر کائنات', roman: 'kaseer kainat', category: 'space' }],
  ['space-time continuum', { urdu: 'زمان و مکان کا تسلسل', roman: 'zaman-o-makan ka tasalsul', category: 'space' }],
  ['interstellar travel', { urdu: 'بین الستاروی سفر', roman: 'bein-ul-sitarvi safar', category: 'space' }],
  ['colonization of mars', { urdu: 'مریخ پر آبادی', roman: 'mareekh par aabadi', category: 'space' }],
  ['terraforming', { urdu: 'زمین سازی', roman: 'zameen saazi', category: 'space' }],
  ['extraterrestrial life', { urdu: 'غیر ارضی زندگی', roman: 'ghair arzi zindagi', category: 'space' }],
  // ─── CULINARY ARTS & WORLD CUISINES (50 entries) ──────────────────────────────
  ['gastronomy', { urdu: 'فنِ طباخی', roman: 'fan-e-tabbakhi', category: 'culinary' }],
  ['sous chef', { urdu: 'نائب باورچی', roman: 'naib bawarchi', category: 'culinary' }],
  ['pastry chef', { urdu: 'حلائی باورچی', roman: 'halai bawarchi', category: 'culinary' }],
  ['confectionery', { urdu: 'مٹھائی کی دکان', roman: 'mithai ki dukan', category: 'culinary' }],
  ['bakery', { urdu: 'بیکری', roman: 'bakery', category: 'culinary' }],
  ['fermentation', { urdu: 'خمیر سازی', roman: 'khameer saazi', category: 'culinary' }],
  ['pasteurization', { urdu: 'جراثیم کشی', roman: 'jaraseem kushi', category: 'culinary' }],
  ['caramelization', { urdu: 'شکر کو پگھلانا', roman: 'shakar ko pighlana', category: 'culinary' }],
  ['reduction culinary', { urdu: 'گاڑھا کرنا', roman: 'garha karna', category: 'culinary' }],
  ['emulsification', { urdu: 'آمیزش', roman: 'aamezish', category: 'culinary' }],
  ['molecular gastronomy', { urdu: 'مالیکیولی طباخی', roman: 'molecular tabbakhi', category: 'culinary' }],
  ['fusion cuisine', { urdu: 'مخلوط کھانے', roman: 'makhloot khane', category: 'culinary' }],
  ['gourmet', { urdu: 'عمدہ خوراک کا شوقین', roman: 'umda khorak ka shoqeen', category: 'culinary' }],
  ['delicacy', { urdu: 'عمدہ غذا', roman: 'umda ghiza', category: 'culinary' }],
  ['appetizer', { urdu: 'بھوک بڑھانے والی چیز', roman: 'bhook barhane wali cheez', category: 'culinary' }],
  ['entree', { urdu: 'اصل کھانا', roman: 'asal khana', category: 'culinary' }],
  ['side dish', { urdu: 'ساتھ کی ڈش', roman: 'sath ki dish', category: 'culinary' }],
  ['dessert', { urdu: 'میٹھا', roman: 'meetha', category: 'culinary' }],
  ['beverage', { urdu: 'مشروب', roman: 'mashroob', category: 'culinary' }],
  ['mocktail', { urdu: 'غیر الکوحل مشروب', roman: 'ghair alcoholic mashroob', category: 'culinary' }],
  ['cocktail', { urdu: 'مشروب کا مرکب', roman: 'mashroob ka murakkab', category: 'culinary' }],
  ['sommelier', { urdu: 'مشروبات کا ماہر', roman: 'mashrobat ka mahir', category: 'culinary' }],
  ['vintage', { urdu: 'عمدہ اور پرانا', roman: 'umda aur purana', category: 'culinary' }],
  ['organic food', { urdu: 'نامیاتی خوراک', roman: 'namiyati khorak', category: 'culinary' }],
  ['vegan', { urdu: 'سبزی خور', roman: 'sabzi khor', category: 'culinary' }],
  ['vegetarian', { urdu: 'سبزی خور', roman: 'sabzi khor', category: 'culinary' }],
  ['gluten free', { urdu: 'گلوٹین سے پاک', roman: 'gluten se pak', category: 'culinary' }],
  ['lactose intolerant', { urdu: 'دودھ سے الرجی', roman: 'doodh se allergy', category: 'culinary' }],
  ['umami', { urdu: 'لذت دار', roman: 'lazzat dar', category: 'culinary' }],
  ['seasoning', { urdu: 'مصالحہ جات', roman: 'masalha jaat', category: 'culinary' }],
  ['marination', { urdu: 'مصالحہ لگانا', roman: 'masalha lagana', category: 'culinary' }],
  ['grilling', { urdu: 'بھوننا', roman: 'bhunna', category: 'culinary' }],
  ['roasting', { urdu: 'بھوننا', roman: 'bhunna', category: 'culinary' }],
  ['baking', { urdu: 'بیکنگ', roman: 'baking', category: 'culinary' }],
  ['braising', { urdu: 'ہلکی آنچ پر پکانا', roman: 'halki aanch par pakana', category: 'culinary' }],
  ['poaching', { urdu: 'ہلکا ابالنا', roman: 'halka ubalna', category: 'culinary' }],
  ['sautéing', { urdu: 'تلنا', roman: 'talna', category: 'culinary' }],
  ['deep frying', { urdu: 'گہرا تلنا', roman: 'gehra talna', category: 'culinary' }],
  ['steaming', { urdu: 'بھاپ دینا', roman: 'bhaap dena', category: 'culinary' }],
  ['blanching', { urdu: 'ہلکا ابالنا', roman: 'halka ubalna', category: 'culinary' }],
  ['plating', { urdu: 'کھانا سجانا', roman: 'khana sajana', category: 'culinary' }],
  ['cutlery', { urdu: 'چھری کانٹے', roman: 'churi kante', category: 'culinary' }],
  ['crockery', { urdu: 'برتن', roman: 'bartan', category: 'culinary' }],
  ['glassware', { urdu: 'شیشے کے برتن', roman: 'shishay kay bartan', category: 'culinary' }],
  ['table manners', { urdu: 'کھانے کے آداب', roman: 'khane kay aadab', category: 'culinary' }],
  ['fine dining', { urdu: 'عمدہ کھانا', roman: 'umda khana', category: 'culinary' }],
  ['street food', { urdu: 'پتھارے کا کھانا', roman: 'patharay ka khana', category: 'culinary' }],
  ['buffet', { urdu: 'بوفے', roman: 'buffet', category: 'culinary' }],
  ['catering', { urdu: 'کھانے پینے کا انتظام', roman: 'khane peene ka intezam', category: 'culinary' }],
  ['recipe', { urdu: 'ترکیب', roman: 'tarkeeb', category: 'culinary' }],
  // ─── SPORTS & PHYSICAL EDUCATION (60 entries) ────────────────────────────────
  ['athletics', { urdu: 'ایتھلیٹکس', roman: 'athletics', category: 'sports' }],
  ['gymnastics', { urdu: 'جمناسٹک', roman: 'gymnastics', category: 'sports' }],
  ['martial arts', { urdu: 'رزمیہ فنون', roman: 'razmiya funoon', category: 'sports' }],
  ['karate', { urdu: 'کراٹے', roman: 'karate', category: 'sports' }],
  ['taekwondo', { urdu: 'تائیکوانڈو', roman: 'taekwondo', category: 'sports' }],
  ['judo', { urdu: 'جوڈو', roman: 'judo', category: 'sports' }],
  ['boxing', { urdu: 'باکسنگ', roman: 'boxing', category: 'sports' }],
  ['wrestling', { urdu: 'کشتی', roman: 'kushti', category: 'sports' }],
  ['archery', { urdu: 'تیر اندازی', roman: 'teer andazi', category: 'sports' }],
  ['fencing', { urdu: 'تلوار بازی', roman: 'talwar bazi', category: 'sports' }],
  ['swimming', { urdu: 'تیراکی', roman: 'teraki', category: 'sports' }],
  ['diving', { urdu: 'غوطہ خوری', roman: 'ghota khori', category: 'sports' }],
  ['rowing', { urdu: 'کشتی رانی', roman: 'kushti rani', category: 'sports' }],
  ['sailing', { urdu: 'جہاز رانی', roman: 'jahaz rani', category: 'sports' }],
  ['cycling', { urdu: 'سائیکلنگ', roman: 'cycling', category: 'sports' }],
  ['mountain biking', { urdu: 'پہاڑی سائیکلنگ', roman: 'pahari cycling', category: 'sports' }],
  ['hiking', { urdu: 'پیدل سفر', roman: 'pedal safar', category: 'sports' }],
  ['climbing', { urdu: 'پہاڑ چڑھنا', roman: 'pahar charhna', category: 'sports' }],
  ['skiing', { urdu: 'برف پر پھسلنا', roman: 'barf پر phisalna', category: 'sports' }],
  ['snowboarding', { urdu: 'سنو بورڈنگ', roman: 'snowboarding', category: 'sports' }],
  ['ice skating', { urdu: 'برف پر اسکیٹنگ', roman: 'barf پر skating', category: 'sports' }],
  ['figure skating', { urdu: 'فگر اسکیٹنگ', roman: 'figure skating', category: 'sports' }],
  ['surfing', { urdu: 'سرفنگ', roman: 'surfing', category: 'sports' }],
  ['skateboarding', { urdu: 'اسکیٹ بورڈنگ', roman: 'skateboarding', category: 'sports' }],
  ['marathon', { urdu: 'لمبی دوڑ', roman: 'lambi dor', category: 'sports' }],
  ['triathlon', { urdu: 'ٹرائیتھلون', roman: 'triathlon', category: 'sports' }],
  ['decathlon', { urdu: 'ڈیکاتھلون', roman: 'decathlon', category: 'sports' }],
  ['paralympics', { urdu: 'پیرا اولمپکس', roman: 'paralympics', category: 'sports' }],
  ['special olympics', { urdu: 'سپیشل اولمپکس', roman: 'special olympics', category: 'sports' }],
  ['referee', { urdu: 'ریفری', roman: 'referee', category: 'sports' }],
  ['umpire', { urdu: 'امپائر', roman: 'umpire', category: 'sports' }],
  ['coach', { urdu: 'کوچ', roman: 'coach', category: 'sports' }],
  ['training', { urdu: 'تربیت', roman: 'tarbiyat', category: 'sports' }],
  ['warm up', { urdu: 'جسم گرم کرنا', roman: 'jism garam karna', category: 'sports' }],
  ['workout', { urdu: 'ورزش', roman: 'varzish', category: 'sports' }],
  ['fitness', { urdu: 'تندرستی', roman: 'tandurusti', category: 'sports' }],
  ['endurance', { urdu: 'قوتِ برداشت', roman: 'quwat-e-bardasht', category: 'sports' }],
  ['stamina', { urdu: 'طاقت', roman: 'taqat', category: 'sports' }],
  ['flexibility', { urdu: 'لچک', roman: 'lachak', category: 'sports' }],
  ['agility', { urdu: 'پھرتی', roman: 'phurti', category: 'sports' }],
  ['sportsmanship', { urdu: 'کھیل کی روح', roman: 'khel ki rooh', category: 'sports' }],
  ['fair play', { urdu: 'دیانتدارانہ کھیل', roman: 'diyanatdarana khel', category: 'sports' }],
  ['tournament', { urdu: 'ٹورنامنٹ', roman: 'tournament', category: 'sports' }],
  ['championship', { urdu: 'چیمپئن شپ', roman: 'championship', category: 'sports' }],
  ['gold medal', { urdu: 'طلائی تمغہ', roman: 'talayi tamgha', category: 'sports' }],
  ['silver medal', { urdu: 'چاندی کا تمغہ', roman: 'chandi ka tamgha', category: 'sports' }],
  ['bronze medal', { urdu: 'کانسی کا تمغہ', roman: 'kansi ka tamgha', category: 'sports' }],
  ['world record', { urdu: 'عالمی ریکارڈ', roman: 'alami record', category: 'sports' }],
  ['stadium', { urdu: 'اسٹیڈیم', roman: 'stadium', category: 'sports' }],
  ['arena', { urdu: 'میدان', roman: 'maidan', category: 'sports' }],
  ['pitch', { urdu: 'پچ', roman: 'pitch', category: 'sports' }],
  ['outfield', { urdu: 'آؤٹ فیلڈ', roman: 'outfield', category: 'sports' }],
  ['infield', { urdu: 'ان فیلڈ', roman: 'infield', category: 'sports' }],
  ['homerun', { urdu: 'ہوم رن', roman: 'homerun', category: 'sports' }],
  ['touchdown', { urdu: 'ٹچ ڈاؤن', roman: 'touchdown', category: 'sports' }],
  ['slam dunk', { urdu: 'سلیم ڈنک', roman: 'slam dunk', category: 'sports' }],
  ['free throw', { urdu: 'فری تھرو', roman: 'free throw', category: 'sports' }],
  ['penalty kick', { urdu: 'پینلٹی کک', roman: 'penalty kick', category: 'sports' }],
  ['offside', { urdu: 'آف سائیڈ', roman: 'offside', category: 'sports' }],
  ['hat-trick', { urdu: 'ہیٹ ٹرک', roman: 'hat-trick', category: 'sports' }],
];

// Append entries
const lastLinePattern = /\[\s*'sensitive content'\s*,\s*\{\s*urdu:\s*'حساس مواد',\s*roman:\s*'hassaas mawad',\s*category:\s*'social_media'\s*\}\s*\]\s*\]\s*;\s*/;

if (lastLinePattern.test(content)) {
    const formattedEntries = newEntries.map(e => `  ['${e[0]}', { urdu: '${e[1].urdu}', roman: '${e[1].roman}', category: '${e[1].category}' }],`).join('\n');
    const replacement = `['sensitive content', { urdu: 'حساس مواد', roman: 'hassaas mawad', category: 'social_media' }],\n${formattedEntries}\n]);`;
    content = content.replace(/\[\s*'sensitive content'\s*,\s*\{\s*urdu:\s*'حساس مواد',\s*roman:\s*'hassaas mawad',\s*category:\s*'social_media'\s*\}\s*\]\s*\]\s*;\s*$/, replacement);
    fs.writeFileSync(filePath, content);
    console.log('Successfully added 610 entries.');
} else {
    console.error('Target content not found at the end of the file.');
    // Try a simpler match for the end of the file
    const endPattern = /\]\s*\)\s*;\s*$/;
    if (endPattern.test(content)) {
        const formattedEntries = newEntries.map(e => `  ['${e[0]}', { urdu: '${e[1].urdu}', roman: '${e[1].roman}', category: '${e[1].category}' }],`).join('\n');
        content = content.replace(/\]\s*\)\s*;\s*$/, `,\n${formattedEntries}\n]);`);
        fs.writeFileSync(filePath, content);
        console.log('Successfully appended 610 entries using fallback.');
    } else {
        console.error('Could not find the end of the Map constructor.');
    }
}
